### PR TITLE
add warning and help text for maxfps fields

### LINKED ISSUE #754: Max FPS and Alarm Max FPS disable when Source Type IP Camera
Mentioned on irc that we should fix this so logging the issue so we remember to get to it. We should be able to manage in the GUI to clear the values and hide the fields when FFMPEG, Remote, cURL and Libvlc Source Types are selected. I assume these sources are only used for IP Cameras?

The other option is to leave the fields as is but make sure the values have no impact, but that could still confuse users.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10055120-max-fps-and-alarm-max-fps-disable-when-source-type-ip-camera?utm_campaign=plugin&utm_content=tracker%2F188329&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F188329&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by knnniggett**
fixes #754 

I don't find this solution visually elegant, and I'm open to suggestions if anyone has other ideas.

Screenshots are incoming....

NOTE that I did experiment with triggering a popup when the user clicked into the maxfps field, but that got annoying real quick.  I settled for a note, in red, appearing to the right of the box.

Also, what you see in the screenshots below does not appear for existing monitors with a type of "local' or "file" since the issue does not affect those types.

### CODE REVIEW

**Comment by knnniggett** [comment]
When creating a new monitor, the only thing new is the "?" link next to the maxfps fields:

screenshot from 2015-08-22 12 41 31

Upon clicking inside either maxfps field, a red note appears that points the user to the help text:

screenshot from 2015-08-22 12 41 40

Click either "?" brings up the follow help text popup:

screenshot from 2015-08-22 12 41 47

**Comment by connortechnology** [comment]
I think it's good enough for now.

**Comment by SteveGilvarry** [comment]
@knnniggett Did you want to resolve the conflicts and I will merge this.

**Comment by knnniggett** [comment]
@SteveGilvarry Conflicts should be fixed now.  Curiously, how did #ff4a174 end up in this pr? Hope it doesn’t matter.

**Comment by SteveGilvarry** [comment]
@knnniggett Something with how you merged it I think, I would have expected to see Merge branch 'master'.

**Comment by SteveGilvarry** [comment]
Looks like it all came out in the wash just fine.

**Pull request merged**
