### PR TITLE
Dark CSS for classic theme

### PR DESCRIPTION
**Pull request by schrorg**
I added a dark CSS for the classic theme. It might help some other people who work in darker environments or who feel better with it.

The only things I changed are some colors in the CSS and a line of JavaScript for the log view. The transition effect for new lines appearing in the log always faded the font color to black. I changed it to fade to the original color instead by getting it from CSS first.

I hope that I have not violated any color specifications for ZoneMinder logo or anything else. Please let me know if i broke or forgot anything.

### CODE REVIEW

**Comment by knnniggett** [comment]
Any chance you could give us a couple screenshots?

Note that autotools is being depreciated.  If memory serves me, cmake just globs everything under the /web folder, but can you verify that we don't need to make any cmake changes?

**Comment by connortechnology** [comment]
Looks fine to me.

**Comment by schrorg** [comment]
I made some screenshots:
console
add_monitor
groups
options
log

**Comment by schrorg** [comment]
CMake seems to get all files in web/ automatically.

For testing I use dpkg-buildpackage on Ubuntu 14.04 (with the ubuntu1204 subdirectory of distros/). It required me to update all the Makefile.am files.

**Comment by knnniggett** [comment]
Excellent.  Thank you for testing.  

@SteveGilvarry is in the process of consolidating and/or updating the Ubuntu distro folders.  We do plan to convert them all to cmake if they are not already.

**Pull request merged**
