### PR TITLE
disable save button when nothing slected. fixes #1322

### LINKED ISSUE #1322: Add input checking / validation when creating a group of monitors.
Currently, it allows you to attempt to create a group, then press SAVE, but if you do not have any monitors selected it gives an SQL error. I think there should be some kind of validation that alerts the user that no monitors are selected, deactivates the SAVE button, or allow it to create an empty names group to add monitors to later.

`SQL-ERR 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'MonitorIds' cannot be null', statement was 'INSERT INTO Groups SET Name=?, MonitorIds=?'`

### PR DESCRIPTION
**Pull request by knnniggett**
Fixes #1322 on my machine. Please test.

### CODE REVIEW

**Comment by connortechnology** [comment]
Um.. what is element.selected?  This is not standard DOM as far as I know.  Is it a jquery thing?

Seems to me it should be element.selectedIndex and we should be able to test for >= 0 (-1 means no selection).

**Comment by knnniggett** [comment]
I'm just winging this php stuff.

I noticed that the selected property was being set for each monitor here:
https://github.com/ZoneMinder/ZoneMinder/blob/master/web/skins/classic/views/group.php#L70

I'm not entirely sure that "if" condition even needs to be in there.

**Comment by connortechnology** [comment]
Oh... the option element has a selected property... but not the select element.
if ( element.selectedIndex >= 0 ) {

can you try that and see if it works?

**Comment by knnniggett** [comment]
sure. give me a sec.

**Comment by knnniggett** [comment]
Ah no, that does not work. The button never enables when I use `if ( element.selectedIndex >= 0 )` or even `if ( element.selectedIndex )`

What does work, is removing that `if` condition altogether.

**Comment by knnniggett** [comment]
The behaviour we are looking for seems to be similar to this:
https://github.com/ZoneMinder/ZoneMinder/blob/master/web/skins/classic/views/js/monitorpreset.js#L10

Since that is not checking element.selectedIndex , I'll just go ahead and remove the the `if` condition.

**Comment by connortechnology** [comment]
Yeah, after reading modern DOM docs... select.value should work just fine.

**Pull request merged**
