### PR TITLE
Fix: Select Layouts on Montage page

### PR DESCRIPTION
**Pull request by IgorA100**
**Preset Layouts should be first in the Layots list**

- Moved list of preset Layouts from montage.js to montage.php
- Changed the definition of the default Layout

### CODE REVIEW

**Comment by IgorA100** [comment]
Please check and approve before use #4014

**Comment by connortechnology** [comment]
Since we may come to the montage page with different selections of monitors selected, maybe by group, perhaps we should have an auto layout option, which tries to guess how many across it should use.  Because once the cookie is set, it won't change. Just a thought.

**Comment by IgorA100** [comment]
> Because once the cookie is set, it won't change. Just a thought.

Thanks for the good idea, I'll think about it.
Maybe you should remove "Freeform" (now there is practically no use for it) and add the "auto" mode you suggest?

**Comment by IgorA100** [comment]
@connortechnology 
Done #4019
I did as you requested :)
I removed the "Freeform" layout because... I find it pointless and added the "Auto" mode

**Pull request merged**
