### PR TITLE
use webvvt to overlay timestamp on videos to videos in timeline and event

### PR DESCRIPTION
**Pull request by liucougar**
honoring Monitor.LabelFormat

also fixed bug which prevented seeking in timeline video preview

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
@liucougar Looks good I will try to check this on the weekend and merge before I do another master merge.

**Comment by liucougar** [comment]
with this new timestamping, I noticed there is a bug in the creation of the recording videos (at least with the videos created by the `record` mode, each of which is about 10 mins long): the first 2-3 seconds of the video is not viewable in either video html5 element in browser nor vlc. in addition, there is 2-3 seconds extra at the end of the video in both html5 video and vlc. I think something is not quite right with the timing info in the recorded videos.

**Comment by SteveGilvarry** [comment]
Keyframe issues I believe

**Comment by liucougar** [comment]
i have 2 seconds key frames, so I guess that makes sense. Do you have any suggestions on how that could be fixed?

**Comment by SteveGilvarry** [comment]
Fifo packet buffer, keep meaning to get to it, that and pre event buffer of
packets.

**Comment by liucougar** [comment]
@SteveGilvarry any update on this please?

**Pull request merged**
