### PR TITLE
Add Socket Support to zmupdate

### PR DESCRIPTION
**Pull request by josh4trunks**
I will report back when I have a chance to test this as working.
Feel free to test and report back in the meantime though =]

### CODE REVIEW

**Comment by connortechnology** [comment]
Looks good except that we really need to start enforcing the use of google code style rules.

**Comment by josh4trunks** [comment]
I'm not familiar with them. What should I reading?

Is there anything I should look at cleaning up for this PR, or are referring to this script in general?

**Comment by josh4trunks** [comment]
Ok, I tested this as working for a few different cases including without a port/socket specified, with a custom port specified, and custom socket specified.

**Comment by knnniggett** [comment]
For the sake of learning, what is the motivator behind this? Why do we want to do this?

**Comment by josh4trunks** [comment]
@knnniggett 
Without the proposed fix, this script will not handle a **ZM_DB_HOST** like `localhost:/path/to/mysql.sock` correctly. It would pass the socket path as a port argument.

**Comment by josh4trunks** [comment]
=]

**Pull request merged**
