### PR TITLE
Mouseover thumbnails on console

### PR DESCRIPTION
**Pull request by jmynheir**
add an option to disable popup when mouseover thumbnails in console.  becomes frustrating to navigate when the popup obscures the links.
preview

### CODE REVIEW

**Comment by connortechnology** [comment]
Something has gone very wrong with this PR.  I think you have made it against release-1.34 branch instead of master.  You will have to redo it.

**Comment by knight-of-ni** [comment]
@jmynheir Very few people are willing to actually do the work to accomplish their suggestions. I appreciate that you took the time to do this. Unfortunately, we can't merge this PR as it is. This PR was generated against our release branch, when it should have been created against the master branch.

I don't see any commits from you in this PR. If you could point me to it, I could probably merge them in for you.

**Comment by jmynheir** [comment]
I tried to add a PR as stated on the forum, I am not fluent in github and
workflow, as I am not a programmer.  Sorry for any confusion I have caused.

**Comment by knight-of-ni** [comment]
That's completely understandable. If you could point out where your code changes are, I can take it from there.

**Comment by knight-of-ni** [comment]
Because of all the code referenced in this PR, anytime someone comments on these bits of unrelated code, it shows up in this PR and I get an email. I'm going to close this PR out and then subscribe to minimize the noise.

The issue this PR attempts to address is already on the roadmap. See #2991 
It will get resolved before the next release.

**Pull request closed without merging**
