### PR TITLE
Freebsd fixes

### PR DESCRIPTION
**Pull request by connortechnology**
This PR allows ZM to build on FreeBSD 10.  Mainly the two issues were sendfile support for which FreeBSD and others have a different parameter list, and the syscall for getting the current pid.

### CODE REVIEW

**Comment by connortechnology** [comment]
Anyone want to review these?  Or can I just merge them myself?

**Comment by connortechnology** [comment]
This somewhat solves #429 . It's still up to the FreeBSD ports people to update to it, but someone can now checkout master+this branch and it will compile and work on freebsd.

**Comment by josh4trunks** [comment]
@connortechnology Thanks for your changes!
Were you planning on updating the FreeBSD port as well? If not, I'll work on it, though I only have moderate FreeBSD porting experiencing so it may take me a while.

**Comment by connortechnology** [comment]
I don't intend to put any further effort into updating FreeBSD ports.  I will happily merge any patches they send.

So go ahead.

**Comment by josh4trunks** [comment]
OK, thanks I'll work on it as time permits.

My preliminary notes are here https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=190268#c7

There's an issue with scripts/ZoneMinder/CMakeLists.txt because FreeBSD needs to use gmake (GNU make) but this can be patched in the FreeBSD port.

**Pull request merged**
