### PR TITLE
added FreeBSD startup script

### PR DESCRIPTION
**Pull request by abishai**
rc.d startup script for ZoneMinder

### CODE REVIEW

**Comment by knight-of-ni** [comment]
Good idea, but I am not sure if you intend for this to be a static file or to be configured by cmake. The ".in" extension implies it needs to be processed, but you have not defined a CMakeLists.txt to do the configuring.

If you intend this to be just a static file, then maybe we ought to put this under /misc.

**Comment by abishai** [comment]
Ports framework uses .in files as well. However if you think the same can be achieved with CMake, I can try it.  
I need to place file this in ${STAGE_DIR}/etc/rc.d. So, I should create CMakeLists.txt with install(), right ?

**Comment by knight-of-ni** [comment]
I think a good start would be to just configure the file with cmake, then install it with the ports framework.

To do that, you need to add `add_subdirectory(distros/freebsd)` to the main CMakeLists.txt file.
You can optionally add the subdirectoy only when ZM_TARGET_DISTRO equals FreeBSD. This will become required if we ever want cmake to install any FreBSD specific file(s) in question.

Create a new CMakeLists.txt file in dostros/freebsd. It should have content similar to this:
```
configure_file(zoneminder.in ${CMAKE_CURRENT_SOURCE_DIR}/zoneminder @ONLY)
```

Then update your zoneminder.in file to use make macros for the paths you are using for `command` and `pidfile`. There are existing make macros for the paths you are using. I just forget what they are at the moment.

Do you have any other files you want to include? Why just this one? I wonder if if makes sense to host all the packaging files and scripts you might use to build the port.

**Comment by abishai** [comment]
Well, I have a readme as well :P Thanks for suggestions, I'll definitely look into existing cmake scripts to make this one and shebangs in proper way!

**Comment by knight-of-ni** [comment]
If you have any questions, feel free to ask in our slack channel. I'm sure we can work this out.

**Pull request closed without merging**
