### PR TITLE
ONVIF: Tenvis TH661 support

### PR DESCRIPTION
**Pull request by jburgess777**
These changes allow zmonvif-probe.pl to detect and determine the correct parameters for a Tenvis TH661 camera.

### CODE REVIEW

**Comment by jburgess777** [comment]
Here is the script output for this camera:

$ zmonvif-probe.pl probe
http://192.168.1.246:8080/onvif/devices, 1.2, (Profile='Streaming', model='C6F0SeZ0N0P0L0', name='IPCAM', location/country='china')

$ zmonvif-probe.pl profiles http://192.168.1.246:8080/onvif/devices 1.2 admin password 
MainProfileToken, MainProfile, H264, 1280, 720, 5, rtsp://192.168.1.246:554/11
SubProfileToken, SubProfile, H264, 640, 352, 5, rtsp://192.168.1.246:554/12

**Comment by connortechnology** [comment]
This looks good to me.

**Comment by knnniggett** [comment]
Don't merge this yet. I'm working on a Perl dependency issue that cropped in either from this pr or in #1346 (more likely).

**Comment by knnniggett** [comment]
The Perl dependency issue was verified to be part of #1349.
Moving on, I see a definite improvement with with this PR. I'm not longer getting messages that look like `ARRAY(0x7191e0)` implying dereferencing issues.

However, I am getting this:
```
sudo zmonvif-probe.pl -v probe
Probing for SOAP 1.1
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/vendor_perl/SOAP/WSDL/Client.pm line 205.
Probing for SOAP 1.2
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/vendor_perl/SOAP/WSDL/Client.pm line 205.
```
That's not very informative, and I have not yet tried to determine the cause of this. 

@jburgess777 If this looks like an easy fix, let me know. If it isn't I may just merge this pr anyway and follow up with a new pr, once we figure out how to resolve this.

**Comment by connortechnology** [comment]
That error happens when warnings are turned on and you use an undefined variable.  It can be eliminated if you init variables to '' or test for undef before outputting them.

**Comment by knnniggett** [comment]
so in this case, $transport->message() is not defined

**Comment by knnniggett** [comment]
And now the error has gone away. I'm going to merge this.

**Comment by jburgess777** [comment]
I don't know what caused the error you reported. If it comes back again I can take a look.

**Pull request merged**
