### PR TITLE
Have cmake take the version from the version file

### PR DESCRIPTION
**Pull request by connortechnology**
Just putting this here.  Maybe no need to merge yet, I may find other things to change as well. Discuss.

This allows us to only have to change version file instead of both version and CMakeLists.txt.  Which is nice.

### CODE REVIEW

**Comment by knnniggett** [comment]
Just to put what we talked about in irc here in writing, what our plans are:
- coordinate with @SteveGilvarry to create an empty, dead-end wiki page which contains the version number we want zmupdate on installed sites to see. Set permissions such that only we can change it.
- coordindate with @kylejohnson to get the url updates.zoneminder.com/version.txt to point to the newly created wiki page, instead of the version file in our github repo
- merge this pr

I believe this will resolve the issues we have surrounding the discussion in #1485

**Comment by pliablepixels** [comment]
Moving this question here (see https://github.com/ZoneMinder/ZoneMinder/issues/1517)

Does this solve the case when building a _pre-release_ package using do_debian, the _filename_ of the package shows a different version?

**Comment by knnniggett** [comment]
Yes! This solves exactly that problem.

**Comment by pliablepixels** [comment]
But how? I just pulled that PR - it does not solve the problem! All that PR does is make sure the version in CMakeLists picks up the version from the version file. The core problem _is_ the version file - which does not say 1.30 for pre-releases (like now). So when I use do_debian to create a package, it creates _1.29*.deb while actually pulling from 1-30rc tag

**Comment by knnniggett** [comment]
Because the overall solution involves more than just this pull request. 
Are you reading all the bullet points stated previously?

We have to get all the zoneminder installations out in the wild to look at a different location for their version number before we can change the version number store in the file "version" in our github repo. Once we do that (see the bullet points), then we will change the file "version" to contain 1.30.0 instead of 1.29.0.

So until all those steps happen, you can't use do_debian.sh without modifying how the script gets its version number, regardless of whether you merge this particular pr into your local branch or not.

**Comment by pliablepixels** [comment]
@knnniggett - right, that is exactly what I was talking about and I had a suspicion we were talking past each other on some points.

My core question, if you could please clarify: In the future, after points a) and b) are addressed, lets say we have a stable v2.30 and you just released v2.31-rc1. Will you be updating https://github.com/ZoneMinder/ZoneMinder/blob/master/version to say 2.31 before 2.31 is released as a stable version? If so, all is good (in the future).

**Comment by knnniggett** [comment]
No, the version number in that file does not change, nor has it ever changed previously, when going from rc1, rc2, ...rcN, and then finally to full release. This is basically a rehash of a much earlier discussion we had about how to differentiate versions of zoneminders between releases. That is up to the package maintainer to do handle that. 

Release candidates are provided as a convenience to the few advanced folks who might want to try it. We aren't pushing these to the masses and are not going to spend a lot of time on our end making sure end users can tell the difference between the different release candidates.

**Comment by pliablepixels** [comment]
sounds good. Then all is fine

**Comment by knnniggett** [comment]
@kylejohnson mentioned in slack that he stopepd update.zoneminder.com from updating the version with the contents of "version" in our github repo so I'm going to merge this. We will find out soon enough if this wasn't the case.

**Pull request merged**
