### PR TITLE
Telemetry Data

### PR DESCRIPTION
**Pull request by knnniggett**
This PR adds a new Perl daemon, zmtelemetry.pl, which will upload user statistics to our Telemetry server. See #1229 for discussion.

Development is complete, but I'm labelling this as Not Ready for Merge for others to view and comment. I expect this to be merged in ~2 weeks.

### CODE REVIEW

**Comment by connortechnology** [comment]
I think it looks fine, and I think we should merge it sooner rather than later.

**Comment by kylejohnson** [comment]
I wanted to wait until I'm double-done with the back end, and that should be tomorrow.

On February 17, 2016 5:58:14 PM MST, Isaac Connor <notifications@github.com> wrote:
>I think it looks fine, and I think we should merge it sooner rather
>than later.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ZoneMinder/ZoneMinder/pull/1292#issuecomment-185484801

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knnniggett** [comment]
Forgot we did not merge this yet. We need to merge this today.

**Comment by connortechnology** [comment]
Any reason to not merge it right now? Let's get this party started.

**Comment by knnniggett** [comment]
That's what I meant. Let's merge this now, before I create the 1.30 release branch

**Comment by kylejohnson** [comment]
When was the last time this was tested?  I'll review the logs when I get in in a few hours.

**Pull request merged**
