### PR TITLE
suppress warnings of killall for FreeBSD

### PR DESCRIPTION
**Pull request by abishai**

### CODE REVIEW

**Comment by connortechnology** [comment]
Under what circumstances does killall put out a warning?

**Comment by connortechnology** [comment]
Oh... if none are matched.

**Comment by connortechnology** [comment]
It will do this under ubuntu as well.

**Comment by abishai** [comment]
If no childs found. I'm getting a lot of them on startup. This warnings go to zoneminder.pid (??!) on my system and breaking rc.d control script.

**Comment by abishai** [comment]
Ubuntu shouldn't be affected - else { already has supression flag

**Pull request merged**
