### PR TITLE
Add option to make TimeStamp larger

### PR DESCRIPTION
**Pull request by schrorg**
This pull request addresses #991. It is basically working but not yet finished.

### CODE REVIEW

**Comment by wambs** [comment]
Hi,

Can you also make the update where you can adjust the time stamp smaller as we.. Its too big on my output.

Kevin

**Comment by Linwood-F** [comment]
Am new to how things are done -- where would a user make the selection of the larger size?

**Comment by schrorg** [comment]
@Linwood-F Until now you have to adjust the constant ZM_TEXT_SIZE in zm_image.h and set it to either 1 (small/normal size) or 2 (double size). And then recompile.

@wambs, I don't understand what you mean with "smaller as we..". Do you want to have a size between the normal size and my large size?

**Comment by Linwood-F** [comment]
@schrorg , Ah, got it.  Thank you.  I was hoping for something I was doing for an undiscovered but (non-building) user accessible technique that I had missed, as adding a new option through all the screens and SQL looks rather daunting and relatively undocumented.

**Comment by schrorg** [comment]
I finished adding the font size option to the user interface. It can be found in the timestamp panel of every monitor.
Everything seems to run smoothly in my test environment, so I would consider this to be finished and ready for merge.

**Comment by connortechnology** [comment]
For the most part, looks good to me.

Couple of things: 
#1, why does this include @pliablepixels API changes?
#2, you don't need to add lines to each language.  You just add it to en_gb and it will fall back to that. Only put actual translations into each translation file.
#3 in Image::Annotate you didn't make the int size a const...
#4 in zm_image.h you seem to have messed up the whitespace on that enum line...

**Comment by schrorg** [comment]
Oops. Sorry for that. I fixed everything.

Lots of english text in all the language files made me assume, I would have to insert the string into every translation.

I'm not sure how exactly @pliablepixels API changes got into my branch. I guess I did a rebase in a wrong way or so. I rebased again (interactive) and leaved out @pliablepixels commits, so everything should be fine again.

**Comment by schrorg** [comment]
I bumped the version to 1.28.102 and re-merged my branch, so that it is up-to-date with the base again.
Has anyone seen any issues with the larger timestamps so far?

**Comment by knnniggett** [comment]
Why are you bumping the version to .102?
Prior to release, we only bump the version when a PR changes the dB schema.

Also, there already is a PR in the works, which is using .102.

**Comment by schrorg** [comment]
Yeah, I was not sure how to deal with the version bump in master so I decided to go one version up with my changes.
I bumped to .103 now and added my SQL changes to zm_create.sql.in.

**Comment by knnniggett** [comment]
Thank you.  I'm going to change this to "Not Ready for Merge" ... not that there is anything you still need to do, but because there is another PR out there that modify's the same files.  Merging the other PR first will be less consuing.

**Pull request merged**
