### PR TITLE
connect needs a +1

### LINKED ISSUE #1526: 'soc' problem again - now with zmf
zmf bind code was forgotten - +1 should be added as with zms
https://github.com/ZoneMinder/ZoneMinder/blob/66a3fef61ebd10c45968a3706021d45d027e28be/src/zm_event.cpp#L275

### PR DESCRIPTION
**Pull request by connortechnology**
fix #1526

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
Nominating for merging to 1.30, any objections?

**Comment by connortechnology** [comment]
Yeah assuming I have managed to add a +1 correctly, I think this should go in.

**Comment by abishai** [comment]
Maybe paste entire solution from zms ? It's checking max length, for example and warnings if it's too long.

**Comment by SteveGilvarry** [comment]
@connortechnology Did you want to implement any of the checking @abishai is talking about, if not I will merge.

**Pull request merged**
