### PR TITLE
Don't install zm.conf if it already exists

### PR DESCRIPTION
**Pull request by connortechnology**

### CODE REVIEW

**Comment by knnniggett** [comment]
Not installing zm.conf at all would potentially prevent someone from receiving needed changes should we add new variables to zm.conf.  Instead of not installing it, can we install it as zm.conf.new?

**Comment by connortechnology** [comment]
Seems reasonable.

**Comment by knnniggett** [comment]
Thanks.

**Comment by connortechnology** [comment]
So actually, renaming it to .new is annoyingly difficult.

**Pull request merged**
