### PR TITLE
Improve filter

### PR DESCRIPTION
**Pull request by connortechnology**
The most important thing this patch does is simplify filters for selecting by Server, by providing a dropdown of the available servers.  

It also makes the Filter.pm code more efficient and easier to read by using a foreach instead of a for loop, resulting in all the $filter_expr->{terms}[$i] becoming $term

It also replaces specifying all the event fields to return with a \* so that they are all available to subsequent object uses.

and of course white space and google code style updates to make it all very confusing.

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
screen shot 2016-09-11 at 3 21 16 pm
Submitting this on a single server install came back with
'SELECT count(E.Id) AS EventCount FROM Monitors AS M INNER JOIN Events AS E ON (M.Id = E.MonitorId) WHERE 1 and ( = 'ZM_SERVER_ID' and E.MonitorId = '1' )'

**Comment by connortechnology** [comment]
Finally got around to updating this, have added the missing piece for web ui filter executing

**Comment by SteveGilvarry** [comment]
Absolutely flat out at work but I promise to build, review and merge this weekend.

**Comment by kylejohnson** [comment]
If you rebase master (git checkout improve_filter && git pull --rebase origin master) on to this branch, all of the tab changes should be cleaned up.

**Comment by kylejohnson** [comment]
Uh oh
`SQL-ERR 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ZM_SERVER_ID' in 'where clause'', statement was 'SELECT count(E.Id) AS EventCount FROM Monitors AS M INNER JOIN Events AS E ON (M.Id = E.MonitorId) WHERE 1 and ( E.StartTime < '2016-11-15 07:25:00' and M.ServerId = ZM_SERVER_ID )'`
2016-11-15-072531_934x357_scrot

**Comment by connortechnology** [comment]
I think I got confused which fork I was updating.   I believe this is now up to date.

**Comment by knnniggett** [comment]
Looks like we have a merge conflict. @connortechnology can you fix?

**Comment by connortechnology** [comment]
I give up..

**Comment by knnniggett** [comment]
I just noticed this had a milestone of 1.30.2. Merging...

**Pull request merged**
