### PR TITLE
Stop monitors when closing montage page

### LINKED ISSUE #4051: An error appears when switching from Montage page to Console page.
**Describe Your Environment**
- Version of ZoneMinder 1.37

`ERR | Error writing packet: Invalid argument | zm_videostore.cpp`

At the moment the Montge page is closed, something probably needs to be stopped.

### PR DESCRIPTION
**Pull request by IgorA100**
Possibly closed #4051

### CODE REVIEW

**Comment by connortechnology** [comment]
This seems good, but what happens when the tab becomes visible again?

**Comment by connortechnology** [comment]
Hmm also doesn't seem to do anything here...

**Comment by IgorA100** [comment]
> This seems good, but what happens when the tab becomes visible again?

Yes, you need to restart the monitors. I'll correct it, BUT!


> Hmm also doesn't seem to do anything here...

Nothing happens because... the code `monitors[i].kill();` does not stop the monitors!

**Comment by IgorA100** [comment]
I made an addition: #4054
But my monitors still don't stop.

**Pull request merged**
