### PR TITLE
Improve test multiserver restart cam.

### PR DESCRIPTION
**Pull request by laerciomotta**
Check if the server is correctly before restart cam

### CODE REVIEW

**Comment by connortechnology** [comment]
This is good, but we might want to also test for the non-multiserver case.  So 

if ( (!ZM_SERVER) or ( ZM_SERVER==$monitor[ServerId}) ) {

**Comment by laerciomotta** [comment]
Nice, I think only in multiserver case.. Sorry!

**Comment by connortechnology** [comment]
Also... I'd I've been wondering if we can use the api to cause the restart to happen on the other server

**Comment by laerciomotta** [comment]
Yes, I think this too..
But I need understand better the code.

**Comment by laerciomotta** [comment]
Change based in your tip.

**Pull request merged**
