### PR TITLE
add some error checking, but fix the call to bind

### LINKED ISSUE #1424: (FreeBSD) Incorrect socket name when binding for zms
A lot of stalled 'soc' files left because clean-up code assumes they should be 'sock'
https://gist.github.com/abishai/2c11cda4db6f045ae1a4b0a9a7cbc6e4

### PR DESCRIPTION
**Pull request by connortechnology**
which really should have a +1 in it.

See http://man7.org/linux/man-pages/man7/unix.7.html

Fixes #1424

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
@connortechnology Merge spaces and I will merge

**Comment by connortechnology** [comment]
done

**Comment by josh4trunks** [comment]
Hey guys, on FreeBSD I am no longer able to view live streams of my cameras with either remote or ffmpeg to an rtsp or mjpeg stream.
This stopped working on commit 413eced onwards; live streams work as expected on cffcbc6.

The backend zoneminder process is still running since I am still producing events. Here's the error in log when I setup a remote/rtsp stream, tell me what else I can provide. Thanks
```
Error while decoding frame 0 | zm_remote_camera_rtsp.cpp | 322
11: 00 00 01 06 e5 01 0a 80 00 00 03 | zm_remote_camera_rtsp.cpp | 323
```

**Comment by connortechnology** [comment]
Check your code.  In my tree, when I merged bind_fixes, git duplicated the locking code instead of replacing it.  So it ends up try to gain a second lock.

**Comment by connortechnology** [comment]
yeah... looks like master is pooched by that merge.

**Comment by connortechnology** [comment]
I have pushed a fix

**Comment by josh4trunks** [comment]
Sweet, it works now!
Gonna work on the mysql socket/port work now

**Pull request merged**
