### PR TITLE
handle disk_free_space error

### PR DESCRIPTION
**Pull request by connortechnology**

### CODE REVIEW

**Comment by knnniggett** [comment]
If there were exactly zero bytes free on the target disk, this would trigger the error message, but what is the likeliness of exactly zero bytes free?

**Comment by connortechnology** [comment]
that's a good point.  Perhaps we should not return 0, but just log the error....

**Comment by kylejohnson** [comment]
My question would be, what made you need to make this change?  Were you hitting a condition where you were seeing a free disk space related error?

**Comment by connortechnology** [comment]
we had a previous discussion about it. #1407

**Comment by SteveGilvarry** [comment]
Resolved this?
> Perhaps we should not return 0, but just log the error....

**Pull request merged**
