### PR TITLE
Corrected DB update version comments, fixed typos, and skin font modification

### PR DESCRIPTION
**Pull request by bodegard**
Corrected version comment to indicate an update from 1.28.108 to 1.28.109

### CODE REVIEW

**Comment by knnniggett** [comment]
I seem to be the only one who prefers the classic skin over flat.
@kylejohnson @connortechnology 
Do either of you have any objections to @bodegard 's making the font size smaller 16->13 in commit 54a1117 ?

**Comment by kylejohnson** [comment]
I too still use the classic over the flat.

Also, this shouldn't have been merged.  It should have been three separate PRs 

1. Corrected DB update version comments
2. fixed typos in BLAH
3. flat skin font modification

**Comment by connortechnology** [comment]
I think we are being a little over-pedantic.  if I can quickly read, understand and verify each little change and it's lack of effect, I think we can handle merging it.

**Comment by kylejohnson** [comment]
You know what?  After looking at the individual commits in this PR - they're small and concise - I have to agree with you.

**Pull request merged**
