### PR TITLE
Fix analysis frame

### PR DESCRIPTION
**Pull request by connortechnology**
So getImageSrc expects a frame array, not an id, or an object.

So I made the frame object be upper case, to distinguish it from the frame array that we loaded from the db, and pass that instead of the frameid.

### CODE REVIEW

**Comment by connortechnology** [comment]
So I had to add a bit more to this.  the view=image had no support for specifying capture or analyse image.
It will now.

**Comment by knnniggett** [comment]
Previous behavior did not require one to click on the image to get the red blobs to appear.

**Comment by connortechnology** [comment]
yeah I got the order of results in iAnalImage ? 'analyse' : 'capture' wrong.  fixed I think.

**Comment by knnniggett** [comment]
works for me.

**Pull request merged**
