### PR TITLE
Fixes #760 in part Clean up CMakeLists.txt

### LINKED ISSUE #760: source code mess
### Some Perl modules contain POD stubs:

~~~~
Below is stub documentation for your module. You'd better edit it!
~~~~

and some modules are undocumented.

### Bad code style

All over the sources there are unusually long lines.
For instance `CMakeLists.txt` files are hard to read and edit because of long lines.
Wrapping is easy enough and it makes code a lot more readable.

Same issues exist in CPP code, etc.

### `cppcheck` errors

~~~~
[zm_image.cpp:644]: (error) Resource leak: outfile
[zm_logger.cpp:540]: (error) Dangerous usage of 'classString' (strncpy doesn't always null-terminate it).
[zm_user.cpp:80]: (error) Mismatching allocation and deallocation: User::monitor_ids
[zm_utils.cpp:81]: (error) Using reference 'format' as parameter for va_start() results in undefined behaviour.
[zm_zone.cpp:908]: (error) Mismatching allocation and deallocation: str_ptr
[zm_zone.cpp:924]: (error) Mismatching allocation and deallocation: str_ptr
~~~~

Perhaps it would be a good idea to routinely use `cppcheck` especially during pre-release clean-up.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10208104-source-code-mess?utm_campaign=plugin&utm_content=tracker%2F188329&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F188329&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by SteveGilvarry**
Addresses some of the issues in #760. Worked fine for me, but please feel free to comment and suggest further improvements
Actions were wrap lines where possible, remove comments from initial commit about goals etc. Update errors to refer to ZoneMinder not zm. No functionality changes

### CODE REVIEW

**Comment by knnniggett** [comment]
I was purposefully holding off on making changes to the CMakeLists.txt because I am working in them right now.  Let's merge my other open pr's first.

**Comment by SteveGilvarry** [comment]
Sorry thought that was done and dusted, but now I look I see it is still not merged

**Comment by knnniggett** [comment]
@SteveGilvarry would you mind re-working this so that it can be auto-merged?

**Comment by SteveGilvarry** [comment]
@knnniggett check this see if looks good. Just had to merge the mm_parms and search path values.

**Comment by knnniggett** [comment]
Holy merge, batman.  Crosses fingers and presses the merge button....

**Pull request merged**
