### PR TITLE
Fix: Elimination of jerks for slideToggle on console

### PR DESCRIPTION
**Pull request by IgorA100**
@connortechnology 

Fixes jerking when hiding the display of the filter panel on the console when the "stickey" mode is enabled.
Try this PR for yourself.
In theory it should work.

### CODE REVIEW

**Comment by connortechnology** [comment]
Honestly this didn't do much for me.  Changing the animation to fast is at least a little less annoying.

**Comment by IgorA100** [comment]
Strange...
I'll look more carefully.

**Comment by IgorA100** [comment]
@connortechnology 

I made more changes.
I checked and now it works fine for me.
Please check again for yourself!

**Comment by IgorA100** [comment]
Now there is no need to worry about the element always having the display=block property.
Isaac, there's no way you couldn't tell the difference. Everything should be smoother now.
I set the mode to fast, as you liked.

**Pull request merged**
