### PR TITLE
process RTSP DESCRIBE response header

### PR DESCRIPTION
**Pull request by knnniggett**
potential fix for #685

### CODE REVIEW

**Comment by connortechnology** [comment]
This looks fine to me.  

Why did you use size_t for i in your for loop?  unsigned int is the usual type...

**Comment by knnniggett** [comment]
No good reason other than that is how the other for loops are set up in zm_rtsp, I was simply copying & pasting

**Comment by sogood007** [comment]
FYI: size_t generally is the correct/better type for value return by size() .  It matters when running in 64b vs 32b.  size_t automatically adjusts. unsigned int will get compilation warning in 64b build and size() return 64b in 64b build.

**Comment by connortechnology** [comment]
uh huh. Thing is, this is just a simple for loop counter.  It is not a pointer.  

I did some reading on the matter... seems it is common practice these days to use size_t.. I'm not convinced though as it is not intuitive.  However I just don't care.  

here is a good article: http://www.codeproject.com/Articles/60082/About-size_t-and-ptrdiff_t

**Pull request merged**
