### PR TITLE
change types and move things around to remove compile warnings

### PR DESCRIPTION
**Pull request by connortechnology**

### CODE REVIEW

**Comment by knnniggett** [comment]
That's an interesting type "off_t".  Seems that type is system dependant. 
For the sake of learning, what lead you to use that?

**Comment by connortechnology** [comment]
off_t is POSIX.  It is what st_size in struct stat is defined as.

**Comment by knnniggett** [comment]
fair enough.

**Comment by connortechnology** [comment]
It is actually a signed type

**Pull request merged**
