### PR TITLE
Update installation procedure for RHEL8

### PR DESCRIPTION
**Pull request by yelnis**
Need to add repository for RPM Fusion
https://rpmfusion.org/

### CODE REVIEW

**Comment by knight-of-ni** [comment]
While we certainly appreciate those willing to take the time update our documentation (there is always a need for this), this PR needs some adjustment.

We already instruct the user to navigate to rpmfusion and install the repo. 

See the first sentence below the section title:
https://zoneminder.readthedocs.io/en/latest/installationguide/redhat.html#how-to-install-zoneminder

However, we do need to advise RHEL9 users to enable the CRB repo. Redhat decided to remove powertools and add crb when they released rhel9.

The RHEL8 instructions should not change.

Really all we need to do here is add the following note, just after the rhel8 note:

```
RHEL/CentOS 9 users must also enable the crb repo:

::

    sudo dnf install dnf-plugins-core
    sudo dnf config-manager --set-enabled crb
```

At some point we should probably remove all reference to centos, since the centos this documentation was written around no longer exists.

**Comment by yelnis** [comment]
@knight-of-ni 
Thanks for your confirmation. My PR is just notify that I couldn't install zm to RHEL8 with this document. Also I found the PowerTools was renamed to powertools, but my company's RHEL8 doesn't work lower case of powertools too. My RHEL is managed & modified by company IT or some vendors, so it would not normal condition. Let me leave comment as just information here.

By the way, RHEL installation section doesn't describe to configure database for mysql. Ubuntu section describes mysql configuration. Could you add mysql configuration to RHEL section?  It would be very helpfull for beginer.

Cheers.

**Comment by knight-of-ni** [comment]
@yelnis 
Sounds like you missed this step in the documentation:
```
Once ZoneMinder has been installed, it is critically important that you read the README file under /usr/share/doc/zoneminder. ZoneMinder will not run without completing the steps outlined in the README.
```
The README steps you through dB config along with several other steps.

**Comment by knight-of-ni** [comment]
Superseded by [ce92b14](https://github.com/ZoneMinder/zoneminder/commit/ce92b14247e22783d6dbdece4b0e8a687748c6e6)

**Pull request closed without merging**
