### PR TITLE
Implement CSRF Mitigation

### PR DESCRIPTION
**Pull request by knnniggett**
Add csrf-magic library to zoneminder, and integrate into zoneminder web forms.
https://github.com/ezyang/csrf-magic

What this library does is generate a token, which is based off the users php session id. If the token submitted with the form does not match the token generated when index.php was first loaded, then the web server returns http 403 with the message "CSRF check failed. Your form session may have expired, or you may not have cookies enabled." You will know it, if you trigger the csrf prevention.

I have given this some testing, and it appears to work. However, ideally every form submit or save button in ZoneMinder should be tested to verify there are no false triggers.

### CODE REVIEW

**Comment by mnoorenberghe** [comment]
If this is used on the "login" action it will break many integrations such as [zmNinja](https://github.com/pliablepixels/zmNinja/blob/71b31f5e6d4a67e2af993a1dc2e0ca77154a83e2/www/js/app.js#L993) and [Home Assistant](https://github.com/home-assistant/home-assistant/blob/2b9fb73032cc3fa48302e4619dcb3323624de472/homeassistant/components/zoneminder.py#L75). Perhaps the "login" action can be exempt for now? A CSRF attack against the login form alone seems like a lesser issue.

Unrelated to the above I would suggest adding a way to opt-out of the CSRF protection unless we're willing to put out a quick point release for any things that it breaks.

**Comment by SteveGilvarry** [comment]
@pliablepixels FYI what would work for zmninja if we were to implement a CSRF token?

I remember at some point the API not having a proper authentication method so we have to logon to web ui and use that session, what is the root cause of that? ZMS?

**Comment by knnniggett** [comment]
@SteveGilvarry @connortechnology @pliablepixels @mnoorenberghe 

I've updated this pr to allow csrf-magic library to be turned off under Options.

Additionally, the csrf check is skipped during a login attempt. I *think* this does not create a way for an attacker to work around the csrf check.... or maybe I've been staring at this so long everything sounds good. Need another set of eyes.

This appears to work with zmNinja, but this will need a ton more resting. Would also like feedback from @mnoorenberghe regarding HA.

Note, that I still think we should change the way the API authenticates as described in #1827

**Comment by connortechnology** [comment]
I will merge to storageareas and test.

**Comment by connortechnology** [comment]
Looks good so far.  Everything appears to work, including zmNinja.

**Comment by knnniggett** [comment]
@pliablepixels @mnoorenberghe 

Just wanted to give you guys a chance to provide feedback before we merge this.
We plan to merge this tomorrow if we do here from either of you.... so we can get 1.30.2 out the door.

**Comment by pliablepixels** [comment]
Late to comment. But I've tested with Isaacs CSRF enabled server. No issues.

**Comment by mnoorenberghe** [comment]
It seems to work fine for me too… I didn't test it's effectiveness but with the action=login exclusion I suggested this works fine for HASS so far. I've enabled it on my server so I'll report any issues.

**Pull request merged**
