### PR TITLE
Add eslint configuration files extending Google's rules

### PR DESCRIPTION
**Pull request by mnoorenberghe**
According to https://github.com/ZoneMinder/ZoneMinder/wiki/Coding-Standards ZM follows Google's coding standards. In order to start to enforce this for JS I've added eslint configuration files extending their rules.

If this is something core devs are interested in I can also setup travis to enforce this and discuss/fix some of the other rules I've disabled for now. I used the `--fix` option to automatically fix some of the straightforward issues for now.

To test this you will need to run:
```
npm install --g eslint eslint-config-google
eslint .
```

### CODE REVIEW

**Comment by connortechnology** [comment]
Thanks for this, I think we will definitely want this.  I am merging it to my branch, but I wouldn't expect anything else until after we get 1.30.2 out.

**Comment by mnoorenberghe** [comment]
> I wouldn't expect anything else until after we get 1.30.2 out.

Could you elaborate on this? Do you mean that you're not accepting new patches on any branch until release? Eslint changes don't have to go into 1.30.2.

**Comment by connortechnology** [comment]
Uh... like I said... I will merge to MY branch... other branches are up to those who maintain those branches.  

We may merge this immediately after 1.30.2 gets released... or we may not.. 

I'm just trying to give you some reasonable expectations, while also telling you that we appreciate your contribution. Right now, we are trying to focus on getting 1.30.2 out, and this will NOT be in it. It likely will be in 1.31.0, but that is not a promise.

**Comment by knnniggett** [comment]
I agree with the premise, but I'd rather hold off on this until 1.31.0.

**Comment by connortechnology** [comment]
Yeah so I merged it to storageareas... and fixed all the complaints there.  Not too bad actually.  In fact, I would prefer if it would be more strict.

**Comment by knnniggett** [comment]
@connortechnology Is this pr ready to merge as-is or did you make further changes when testing in your storage areas branch?

**Comment by connortechnology** [comment]
It is fine as-is

**Pull request merged**
