### PR TITLE
fix setButtonStates.  The checkboxes are an array.

### PR DESCRIPTION
**Pull request by connortechnology**
I found that the edit and delete buttons didn't become enabled... this fixes that.  

checkboxes form an array, so setButtonStates must check in the array as well.

### CODE REVIEW

**Comment by knnniggett** [comment]
I'm pretty sure I've noticed this, but I can't remember where.

**Comment by connortechnology** [comment]
When you check one of the checkboxes, does the line get highlighted?  Cuz it should. But it doesn't for me without this PR.

**Comment by knnniggett** [comment]
Well I think so. See screenshot.

screenshot from 2016-03-03 17-13-56

**Comment by connortechnology** [comment]
Yeah that looks right.  I don't really understand how it could be working though.

More investigation before merging.

**Comment by knnniggett** [comment]
Does your web browser debugging console reveal any clues?

**Comment by connortechnology** [comment]
I'll work on this tomorrow.

**Comment by connortechnology** [comment]
I'm not able to reproduce the issue I was having that day.  So this might be unneccsary.

**Pull request closed without merging**
