### PR TITLE
introduce htmlselect as an alternative to buildselect

### PR DESCRIPTION
**Pull request by connortechnology**
I don't like buildselect. 

This introduces a simple function that takes a name, contents, selected value, etc.. and returns a string for the select.

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
@connortechnology Is it just me or is this introducing new function with nothing actually using it?

**Comment by connortechnology** [comment]
That is exactly what it is. 

I have used this function extensively in storageareas.  I find it much more intuitive than buildselect.

I try to keep these PR's very small

**Comment by SteveGilvarry** [comment]
@connortechnology update this and I will merge it since it has no impact until we start to use it, just make mention of it needing a test when you submit a PR that uses it.

**Comment by connortechnology** [comment]
done

**Pull request merged**
