### PR TITLE
Delete XML and Mobile skins and remove eyeZM specific config

### PR DESCRIPTION
**Pull request by SteveGilvarry**
Ripping out XML and Mobile skins as noted in release notes. Also removed all the eyeZM specific configuration and documentation. Hopefully I got it all.

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
Autotools failed, cause I assume it will be gone also.

**Comment by knnniggett** [comment]
I'm onboard with this. My only concern is timing. We plan to create a 1.30 release candidate on Monday, and then release 1 week later. I'd suggest we merge this, following the creation of the 1.30 release candidate,

**Comment by kylejohnson** [comment]
I am OK with getting this into our 1.30 release.  We've given the heads up in the last release message, and these changes appear innocent enough.

**Comment by knnniggett** [comment]
I have merged this during our Monday night meeting since we have push out our next release date.

**Pull request merged**
