### PR TITLE
auth_key api for different situations

### PR DESCRIPTION
**Pull request by pliablepixels**
#2089 

@connortechnology  - take a look.

Seems to work for me, but I noticed that `User.Password` actually stores the MD5 encoded password, not the real password. So `&user=&pass=` pbly won't work - I suppose we need to load some other model for the password?

### CODE REVIEW

**Comment by pliablepixels** [comment]
ok, so `&pass=` is by design, not supposed to send the password, as its never stored in raw form. I'll modify the PR to return a token `REPLACEPASSWORD` so the user knows he needs to replace it with their own. Better then not returning `&pass=` because then the API recipient needs to figure out if it was plain setting.

**Comment by pliablepixels** [comment]
@connortechnology still an issue

When we use this from Curl (or zmNinja) I see this error (and then the array)

```
Notice (8): Undefined index: passwordHash [/usr/share/zoneminder/www/includes/auth.php, line 107]
Code Context

function generateAuthHash( $useRemoteAddr ) {
  if ( ZM_OPT_USE_AUTH and ZM_AUTH_RELAY == 'hashed' and isset($_SESSION['username']) and $_SESSION['passwordHash'] ) {
generateAuthHash - /usr/share/zoneminder/www/includes/auth.php, line 107
HostController::getAuthKey() - APP/Controller/HostController.php, line 43
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
AppController::invokeAction() - APP/Plugin/Crud/Lib/CrudControllerTrait.php, line 31
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 107
{ "auth_key": "auth=", "append_password": 0 }
```

**Comment by pliablepixels** [comment]
There are other issues with this API, that don't show up in the browser. But shows up on curl and zmNinja.

Calling this API multiple times results in other errors like "session already started, ignoring session_start()" and other stuff.

Needs more testing. Not ready for us

**Comment by connortechnology** [comment]
I don't think you need to do all the Config lookups.  I think you can use the defines just like in the regular UI.  

If auth=plain, then we store the password in the session, unhashed.  If we are using auth=hashed then we store passwordHashed in the session as the hashed password.  If we switch auth methods after logging in from plain to hashed, then the session will not have the unhashed password in the session.  

auth=plain is inherently unsafe.  We should really get rid of all of it, and use actual public key cryptography to encrypt a hash.

**Pull request merged**
