### PR TITLE
fixes for event delete. 

### PR DESCRIPTION
**Pull request by pliablepixels**
Work in progress. Deleting an event is calling wrong commands for frame delete. I'm working on this and will keep pushing PRs till I solve.

### CODE REVIEW

**Comment by pliablepixels** [comment]
verified, works. ready for merge.

**Comment by kylejohnson** [comment]
Fairly certain this behaviour is caused by #663.  The real fix is to get #663 merged.

**Comment by connortechnology** [comment]
Ok, so this point is that the frames need to be deleted first, right? 

Seems to me the Event->delete function should just delete the frames first... 

maybe I'm missing the bigger picture.

**Comment by kylejohnson** [comment]
This has been fixed in #1080

**Pull request closed without merging**
