### PR TITLE
Fix build warnings specific to h264 branch

### PR DESCRIPTION
**Pull request by SteveGilvarry**
Got sick of watching warnings scroll past me while building

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
Somethings missing here, both versions build fine locally...

**Comment by knnniggett** [comment]
Here is what Travis says:
```
/home/travis/build/ZoneMinder/ZoneMinder/src/zm_videostore.cpp:155:34: error: expected ‘)’ before ‘PRId64’

/home/travis/build/ZoneMinder/ZoneMinder/src/zm_videostore.cpp:164:4: warning: spurious trailing ‘%’ in format [-Wformat]

/home/travis/build/ZoneMinder/ZoneMinder/src/zm_videostore.cpp:164:4: warning: too many arguments for format [-Wformat-extra-args]
```
That message doesn't look too bad.

**Comment by SteveGilvarry** [comment]
Having another go, just annoying as they are all building locally without issue.

**Comment by SteveGilvarry** [comment]
I will PR again once I get it working on my own Travis account.

**Comment by SteveGilvarry** [comment]
I am starting to think gcc version issue, maybe whatever travis runs doesn't do these macro things

**Comment by SteveGilvarry** [comment]
OK sorry about close and reopen but it does pull in any branch updates on reopen, just didn't update until I closed it again

**Pull request merged**
