### PR TITLE
Apply Tooltip to objects with [data-toggle="tooltip"] & [title] attributes (skin.js)

### PR DESCRIPTION
**Pull request by IgorA100**

### CODE REVIEW

**Comment by IgorA100** [comment]
It appears unsuccessfully in the image (at the very bottom and a scroll bar appears), and requires improvement.

**Comment by connortechnology** [comment]
What is the point of supporting data-tooltip in addition to title?

**Comment by IgorA100** [comment]
I wanted to make the title more beautiful

**Comment by connortechnology** [comment]
I get making titles more beautiful, do we have anything with data-toggle=tooltip?  Why not just use title?

**Comment by IgorA100** [comment]
> I get making titles more beautiful,

Great.

> do we have anything with data-toggle=tooltip?

No.

> Why not just use title?

Yes, you are right.
Not the best idea came to my mind with Tooltip

**Pull request closed without merging**
