### PR TITLE
cmake - use perl INSTALLDIRS

### PR DESCRIPTION
**Pull request by knnniggett**
This PR takes a more traditional approach to installing zoneminder's Perl modules via INSTALLDIRS & DESTDIR paramters, rather then LIB & PREFIX, which are not recommended according to makemaker documentation.

This is essentially proof on concept stage.  I'm looking for feedback from non-Redhat distros.
The intent is to install zoneminder Perl's modules into the distro's Perl "vendor" folders, regardless of the installation method.  

The specific folder the modules go into will vary with each linux disto.  It can be viewed like so:
```
perl '-V:install.*' | grep installvendorlib
```
What needs to be verified is:
1) the build succeeds
2) the perl modules end up in the intended folder

### CODE REVIEW

**Comment by onlyjob** [comment]
Almost perfect except that it installs templates `*.pm.in` along with generated modules.

**Comment by onlyjob** [comment]
Another minor remark is about code style -- pretty much all code standards begin with avoiding long lines which is almost universally recognised as best practice. A little code wrapping would be helpful...

**Comment by knnniggett** [comment]
Well, that's good news.
I thought I noticed the input files were getting copied over, but I'm not sure how many though. Are they all being copied over from every folder or just the input files under the /scripts/ZoneMinder?
I should be able to clean that up without too much problem.

I've read all the issues you've posted, including the one about code style.  Both time & learning curve prevent me from knocking them all out quickly.  For now, I'd prefer to stick with the existing style and then address the whole thing at once at a later time.

**Comment by onlyjob** [comment]
Extra templates goes to `usr/share/perl5/ZoneMinder`, notably `Base.pm.in`, `Config.pm.in`, `ConfigData.pm.in` and `Memory.pm.in`.

Thank you. As far as I'm concerned there are no urgent issues (although I'm a bit worried about #783 as we probably still didn't do enough to prevent data loss..).

I just have a feeling that very-long-lines code formatting issue is actually slowing everybody down... Well maybe it is just me but I find this issue a bit irritating... What if I try to push some safe code-style-only pull requests? I hope you won't mind...

**Comment by knnniggett** [comment]
.in files should no longer be copied into the staging folder with the latest commit.

This required changing from a cmake `execute_process` to a cmake `file COPY` command since the former did not support filtering via pattern.

Redhat's rpm build process does not run out-of-source so I can't test this commit directly.

**Comment by knnniggett** [comment]
@onlyjob Would you mind testing this again with the latest commit?  The previously mentioned .in files should not leave the source folder.

**Comment by onlyjob** [comment]
Sorry for delay. With a2d9c0c no `.pm.in` files are installed. All good, thank you.

**Comment by knnniggett** [comment]
@barjac @PX03AFK 

Gentlemen,
This pull request represents a change in the way zoneminder's Perl modules are built using cmake.  The end result should not be any different for your packages than previous.  I thought I'd give you guys any opportunity to verify this is indeed the case before our next release.

Things to verify are:
1) The build completes w/o error
2) Perl modules are installed into your distro's perl vendor folders (should be the same folders you have been using).

Note that these cmake variables have been removed:
ZM_PERL_USE_PATH
ZM_PERL_SUBPREFIX

they have been replaced with these:
ZM_PERL_MM_PARMS
ZM_PERL_SEARCH_PATH

I don't expect you to need to use these new variables. Let me know if you do.

I will wait a few days to hear from you before I look to merge this into master.

**Comment by barjac** [comment]
All OK here :)

**Comment by mastertheknife** [comment]
Back then when i wrote that stuff, i did it because i didn't want MakeMaker to install those perl modules directly into the system, but rather let cmake do it, that way its nicely integrated and in full control of cmake, so things like "make uninstall" work properly.

Whatever directory you choose, do not forget to update perl's search path, just in case its not already in the include search path.

**Comment by knnniggett** [comment]
@mastertheknife Nice to see you pop in.

This PR keeps the same process of using makemaker to install to a temporary output folder and then let cmake install into buildroot.  It just uses different makemaker parameters to achieve the same end result.  This was done to resolve #769 .  

By default, it will always install into the destination distro's perl vendor folders so I don't expect any issues with Perl's search path.  Preliminary testing on redhat and debian based distros looks good.

If the end user chooses, he/she can override this by supplying custom makemaker parameters along with a folder name to add to perl's search path.

Another, related perl issue, #753 
Perl no longer supports "make uninstall" of perl modules, and this is apparently by design. Naturally, that only affects those who build from source.  What I plan to do is update the documentation to instruct those who build from source to supply the UNINST=1 makemaker parameter. That will tell perl to search for and delete any perl modules with the same name that are already installed.

**Comment by PX03AFK** [comment]
I'm way behind on doing anything with this.  I'll try to get back to it soon
and note the points made.

 

David 

 

  _____

**Comment by knnniggett** [comment]
This is ready to merged into master, to receive additional testing.

**Pull request merged**
