### PR TITLE
initial OSX port - baby steps - compile & make only

### PR DESCRIPTION
**Pull request by pliablepixels**
As of now, it just compiles, and makes. Individual process 'run' from the command line 
~~Polkit has been commented out~~, make install and packaging needs to be ported.

### CODE REVIEW

**Comment by knnniggett** [comment]
Thoughts on this one?
I like the idea of running on a mac, but I'd rather not merge this if no one is going to maintain it.

**Comment by pliablepixels** [comment]
Yup, I think @SteveGilvarry mentioned he may want to take it forward but not sure. 
I wouldn't be taking this forward anytime soon, so please feel free to make a call.

**Comment by SteveGilvarry** [comment]
I think maybe we can merge to a feature branch, changes to readme preclude master merge of this PR. It would be be nice to offer, but like @pliablepixels need to bring up a VM so I don't affect main install.

**Comment by connortechnology** [comment]
I actually own a Mac now so I might be able to do some support for this branch going forward.

**Comment by marcosscriven** [comment]
May I ask if anyone here has considered just using Docker? It's now properly supported on OS X.

**Comment by knnniggett** [comment]
I'm going to close this one out for housekeeping purposes. 

If anyone is interested in continuing development on this, perhaps @pliablepixels can hang on to his "osx-port" branch over in his fork of ZoneMinder.

**Pull request closed without merging**
