### PR TITLE
Fixes #1584. I've just copied the relevant functions from ffmpeg sour…

### LINKED ISSUE #1584: build failed
I following next steps:

```

ubuntu@vm-kzhuykov:~/dev$ git clone https://github.com/ZoneMinder/ZoneMinder.git ZMT
Cloning into 'ZMT'...
remote: Counting objects: 62294, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 62294 (delta 17), reused 0 (delta 0), pack-reused 62249
Receiving objects: 100% (62294/62294), 50.13 MiB | 1.65 MiB/s, done.
Resolving deltas: 100% (45555/45555), done.
Checking connectivity... готово.

ubuntu@vm-kzhuykov:~/dev$ cd ZMT
ubuntu@vm-kzhuykov:~/dev/ZMT$ git submodule update --init --recursive
Submodule 'web/api/app/Plugin/Crud' (https://github.com/FriendsOfCake/crud.git) registered for path 'web/api/app/Plugin/Crud'
Cloning into 'web/api/app/Plugin/Crud'...
remote: Counting objects: 47112, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 47112 (delta 21), reused 0 (delta 0), pack-reused 47078
Receiving objects: 100% (47112/47112), 10.49 MiB | 4.72 MiB/s, done.
Resolving deltas: 100% (34601/34601), done.
Checking connectivity... done.
Submodule path 'web/api/app/Plugin/Crud': checked out 'c3976f1478c681b0bbc132ec3a3e82c3984eeed5'

ubuntu@vm-kzhuykov:~/dev/ZMT$ docker build --no-cache .
Sending build context to Docker daemon 33.52 MB
Step 1 : FROM ubuntu:trusty
 ---> 0ccb13bf1954
Step 2 : MAINTAINER Kyle Johnson <kjohnson@gnulnx.net>
 ---> Running in 55b531aa641c
 ---> b41ed7ef6d23
Removing intermediate container 55b531aa641c

...................................................................................................

Step 7 : RUN make && make install
 ---> Running in 352b393100ea
Scanning dependencies of target zm
[  2%] Building CXX object src/CMakeFiles/zm.dir/zm_box.cpp.o
[  4%] Building CXX object src/CMakeFiles/zm.dir/zm_buffer.cpp.o
[  6%] Building CXX object src/CMakeFiles/zm.dir/zm_camera.cpp.o
[  8%] Building CXX object src/CMakeFiles/zm.dir/zm_comms.cpp.o
[ 10%] Building CXX object src/CMakeFiles/zm.dir/zm_config.cpp.o
[ 12%] Building CXX object src/CMakeFiles/zm.dir/zm_coord.cpp.o
[ 14%] Building CXX object src/CMakeFiles/zm.dir/zm_curl_camera.cpp.o
[ 16%] Building CXX object src/CMakeFiles/zm.dir/zm.cpp.o
[ 18%] Building CXX object src/CMakeFiles/zm.dir/zm_db.cpp.o
[ 20%] Building CXX object src/CMakeFiles/zm.dir/zm_logger.cpp.o
[ 22%] Building CXX object src/CMakeFiles/zm.dir/zm_event.cpp.o
[ 24%] Building CXX object src/CMakeFiles/zm.dir/zm_exception.cpp.o
[ 26%] Building CXX object src/CMakeFiles/zm.dir/zm_file_camera.cpp.o
[ 28%] Building CXX object src/CMakeFiles/zm.dir/zm_ffmpeg_camera.cpp.o
/ZoneMinder/src/zm_ffmpeg_camera.cpp: In member function 'int FfmpegCamera::OpenFfmpeg()':
/ZoneMinder/src/zm_ffmpeg_camera.cpp:241:67: error: 'av_dict_parse_string' was not declared in this scope
   ret = av_dict_parse_string(&opts, Options().c_str(), "=", ",", 0);
                                                                   ^
make[2]: *** [src/CMakeFiles/zm.dir/zm_ffmpeg_camera.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/zm.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c make && make install' returned a non-zero code: 2
ubuntu@vm-kzhuykov:~/dev/ZMT$
```

anyone can test this?

### PR DESCRIPTION
**Pull request by connortechnology**
Fixes #1584. I've just copied the relevant functions from ffmpeg source.  Please review carefully before merging, as I may have screwed up the version check or something.

### CODE REVIEW

**Comment by zhuykovkb** [comment]
build success!

**Comment by knnniggett** [comment]
As one might expect, this builds fine against:
CentOS 6 - ffmpeg 2.6.4
CentOS 7 - ffmpeg 2.8.7
Fedora 24 - ffmpeg 3.0.2

We await word from @SteveGilvarry for his blessing

**Comment by SteveGilvarry** [comment]
Should the version check be one point higher for libav and also do it for ffmpeg on 52.17. I guess trusty is the oldest and also libav only. Unless anyone has back ported ffmpeg, or even a newer libav.
2013-01-25 - e7e14bc / 38c1466 - lavu 52.17.100 / 52.7.0 - dict.h
  Add av_dict_parse_string() to set multiple key/value pairs at once from a
  string.

**Comment by knnniggett** [comment]
There are ffmpeg ppa's out there built for trusty, but I don't know how reliable the package builders are. The last one I tried was missing the libavXXXXXX.so symlinks, pointing to the actual library files, thus preventing cmake from finding it with the find_library command. Perhaps @connortechnology would be willing to host ffmpeg in his ppa in a similar fashion to what I do in zmrepo.

**Comment by connortechnology** [comment]
You know... packaging ffmpeg might be a good idea.  Might allow us to deprecate versions of ffmpeg earlier.
Might also mean we don't need this PR.

**Comment by connortechnology** [comment]
@SteveGilvarry regarding the version check, my brain really wobbles with these version checks between ffmpeg and libav and all.  If you understand it, please help me out and fix that up or tell me exactly what it needs to be or something.

**Comment by SteveGilvarry** [comment]
Like this, probably quicker for you to add than me to get PR branch and push to it.
LIBAVUTIL_VERSION_CHECK(52, 7, 0, 17, 100)

Versions are Major, MinorLibav, MicroLibav, MinorFFMpeg, MicroFFmpeg

FFmpeg made their Micro >=100 so pretty easy to tell which is which.

**Comment by knnniggett** [comment]
@SteveGilvarry the copy_av_dict_parse_string_from_ffmpeg branch is in the main zoneminder repo, rather than iconnor's fork, so you can push to it easily. :-)

**Comment by SteveGilvarry** [comment]
Looks good.
Actually @connortechnology can you try move away from doing that, origin should be your fork and upstream zoneminder/zoneminder. Keeps https://github.com/ZoneMinder/ZoneMinder/branches cleaner so we only have feature or release branches.
You can pull any existing branches to your fork, so no need to worry about losing stuff.

**Comment by connortechnology** [comment]
Honestly I don't know if I can.  I keep trying.  But then it takes me hours to do a minutes work.  I'll keep trying.  Sometimes though, these branches are meant to be collaborative.  And branches are easily cleaned up.

**Pull request merged**
