### PR TITLE
Calculation of Scale before the start of monitors. Montage page

### LINKED ISSUE #4033: Ram use in firefox on montage is significantly more than chrome.

### PR DESCRIPTION
**Pull request by IgorA100**
Prevents large consumption of network traffic when monitors start
Possibly fixes #4033

### CODE REVIEW

**Comment by IgorA100** [comment]
Please test the closure of issue #4033

**Comment by connortechnology** [comment]
Uncaught ReferenceError: movableMonitorData is not defined

**Comment by IgorA100** [comment]
I made changes. Try again.

**Comment by IgorA100** [comment]
What about the memory used?
Has it gotten better or is there still a lot of memory usage when going to the Montage page?

**Pull request merged**
