### PR TITLE
remove set height on the menu bars, fixing flow issues

### PR DESCRIPTION
**Pull request by connortechnology**

### CODE REVIEW

**Comment by knnniggett** [comment]
I'm having trouble visualizing this one. Does this fix an issue you were experiencing?

**Comment by connortechnology** [comment]
Might be a flat theme thing only due to the larger font sizes.

**Comment by kylejohnson** [comment]
I vote that we hold off on these console fixes until my PR is in.  I'm pretty much completely reworking the way that tabs and menu bars work
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by connortechnology** [comment]
I'm concerned that your changes are going to break too much and won't be going in for a long time.

**Comment by SteveGilvarry** [comment]
I really see no issue to hold off, this is fixing an issue now, and @kylejohnson will replace it completely at some point. Fair enough if @connortechnology was wholesale rewriting things, but this is a tweak.

**Pull request merged**
