### PR TITLE
Multi server

### PR DESCRIPTION
**Pull request by connortechnology**
Some fixes for database logging/filtering of logs based on Server.

### CODE REVIEW

**Comment by connortechnology** [comment]
Hopefully fixes #1214

**Comment by knnniggett** [comment]
Hmmm... something is still going on. The web log is no longer populating. I have not yet found an error message to describe the problem though. Still looking.

**Comment by knnniggett** [comment]
@connortechnology 
I discovered an important clue:
If I add "localhost" as an entry under the Servers tab, the web log immediately springs to life.

**Comment by connortechnology** [comment]
possibly.  I will look closer.

**Comment by connortechnology** [comment]
I  really think we should default to only showing a subset of the log when you bring up the web log.  Showing the whole thing just kills firefox.   I'm thinking like the most recent 1000 items or something.

**Comment by knnniggett** [comment]
Hmmm.... no I think I was mistaken. Changing log.Server to log.ServerId causes the Server column to show the ID, which in my case "0", rather than the Server name.

**Comment by connortechnology** [comment]
I think 71 is correct.  The log has two server-related fields, ServerId which is the integer id #, and Server which is the text name.  the text name gets filled in in ajax/log.php.  

I am wondering if your issue was having a value in ServerId, but not having an entry in the Servers table.  We have no foreign keys in our schema, so that could happen.  Really need to improve our schema.  

Anyways, I have added a check which should make it not fail in this case.  Just testing before I commit and PR.

**Comment by knnniggett** [comment]
Excellent. We are working now.

**Pull request merged**
