### PR TITLE
Trying to completely get rid of jiggling montage layout (montage.js)

### PR DESCRIPTION
**Pull request by IgorA100**

### CODE REVIEW

**Comment by IgorA100** [comment]
This is an improvement #4031
Please check.

**Comment by connortechnology** [comment]
Still pretty jiggly, but it settles, so I'm fine with it.

**Comment by IgorA100** [comment]
I get no more than 1 scrollbar switch.

**Comment by IgorA100** [comment]
If you are satisfied, it is advisable to approve this PR, otherwise I am starting to get confused....

**Comment by connortechnology** [comment]
For some reason merging this in addition to other  merges has broken the layout again. It might have been my implementing an auto-scale for initial load.

Screenshot_20240523_135119

**Comment by IgorA100** [comment]
@connortechnology 
You changed a lot in my code.
I'm not ready to find a reason right now.
  from Freeform renamed to Auto In DB? If not, there will be problems. I deliberately left this code temporarily.
I don’t yet know the consequences of this commit https://github.com/ZoneMinder/zoneminder/commit/b63412ad240cab8e13e7b8cf4291709cad1a5cec and others.

There was no need to make that many changes to the code at this point. First, you need to “test” the code so that there are no bugs, and only then do refactoring.

I need to completely update my ZM and do the research all over again.
Forgive me, this is just my IMHO.

**Pull request merged**
