### PR TITLE
Align Method description to what it is actually doing

### PR DESCRIPTION
**Pull request by SteveGilvarry**
Makes it hard for people to know what they are doing with the descriptions from Remote camera, so changed them to line up with FFmpeg option they are controlling. Does also impact libvlc, but these descriptions are closer also. Only fixing as it annoyed me.

### CODE REVIEW

**Comment by connortechnology** [comment]
I like this, but I think we should actually say that they might see corrupted images with UDP... I think those code makes TCP the default, right?  Which I agree with.   So maybe say that UDP is lighter weight but may cause image corruption.  Also... I think the word lower is unnecessary and will confuse noobs.

**Comment by SteveGilvarry** [comment]
I actually want to find someone with UDP corruption to try fifo_size as a fix. But I will mention it can have issues against the UDP help text.

**Comment by connortechnology** [comment]
Oh I have it... I use TCP with my cameras... but I can test.

**Comment by connortechnology** [comment]
Looks good to me.

**Comment by connortechnology** [comment]
Maybe we could even merge this for 1.30.2.

**Comment by SteveGilvarry** [comment]
Nah it missed cutoff, unless everyone else wants to.

**Comment by knnniggett** [comment]
Aw, what the heck.

**Pull request merged**
