### PR TITLE
Fix: Don't specify "sizeToContent: true" when initializing GridStack on Montage page

### PR DESCRIPTION
**Pull request by IgorA100**
Additional verification is required, including on Custom layouts 
I haven't tested everything. Maybe something will break somewhere....
Possible closure #4127, but I'm not sure.

### CODE REVIEW

**Comment by IgorA100** [comment]
This PR slightly violates the sort order different from the console

**Comment by IgorA100** [comment]
Sorting should now work correctly.

**Comment by connortechnology** [comment]
Some missing pieces in there, I've fixed them up but you may  want to review my fixes.

**Comment by connortechnology** [comment]
Hasn't made a big difference for #4127

**Comment by IgorA100** [comment]
> to review my fixes

I looked at it, everything is fine.
Thanks for the help.
My montage.js file is very heavily modified now and due to this there were some stupid mistakes when transferring the code.

**Pull request merged**
