### PR TITLE
Show error message upon unsuccessful login. Fixes #1648

### LINKED ISSUE #1648: Failed login needs more text/explanation of what happened instead of just staying on the login screen

### PR DESCRIPTION
**Pull request by kylejohnson**
This PR pulls in a couple commits from #1665 which support restyling the login page.

* Includes bootstrap glyphicons as they're used in the error message.
* Failure check is done via a simple test in login.js.php and login.js.
   The 'view' param will only be set (to 'postlogin') if the login page
   has refreshed due to a failed login.  Otherwise you're directed to
   the console view.

2016-11-10-225336_494x407_scrot
2016-11-10-225325_544x384_scrot

### CODE REVIEW

**Comment by kylejohnson** [comment]
The number of changes is a bit misleading.  288 of the changes come from the inclusion of `web/fonts/glyphicons-halflings-regular.svg `

**Comment by connortechnology** [comment]
I'm ok with the extra stuff, but to be picky, it doesn't need to be in here.  Looks nice though.  

It would be nice to have a more generic error messaging system in place but that's for another day.  

I'll give it a little more time for others to weigh in, but I'm happy to merge it.

**Comment by knnniggett** [comment]
I am not familiar with bootstrap, but glyphicon-exclamation-sign icon failed to load on my system....

screenshot from 2016-11-13 14-49-29

**Comment by kylejohnson** [comment]
@knnniggett  Do you have a `fonts` directory in ZM's webroot?
```
ajax        cmake_install.cmake  events    images     js        README.md  tools
api         CMakeLists.txt       fonts     includes   lang      scripts    views
CMakeFiles  css                  graphics  index.php  Makefile  skins
```
2016-11-14-092732_1269x491_scrot

**Comment by knnniggett** [comment]
No, I do not have a fonts folder in zoneminder's web root, nor does there appear to be a fonts folder in the source tree. Where does this folder come from?

**Comment by kylejohnson** [comment]
Hm, there should be one - it was added in commit 0800a69a5769c09e15af07b807e06ac763c27d6c.

**Comment by kylejohnson** [comment]
@knnniggett The fonts dir wasn't in the cmakelist - it is now.

**Pull request merged**
