### PR TITLE
tabs to spaces

### PR DESCRIPTION
**Pull request by connortechnology**
The ongoing work to fix the whitespace/google code style

### CODE REVIEW

**Comment by kylejohnson** [comment]
I think a criteria for this getting merged is that the number of changes (additions and deletions) stays equal; that'll help us to clearly see that this PR was only for what it should be.

**Comment by connortechnology** [comment]
I don't see why the # of lines would change.  I think git is just being stupid.

**Comment by connortechnology** [comment]
yeah something must have gone wrong. let me fix it.

**Comment by connortechnology** [comment]
So git diff -w master shows no changes....

**Comment by connortechnology** [comment]
Oh hey, # of changes is the same.... let's merge.

**Comment by connortechnology** [comment]
I'm so confused now which branch is which, but I think I've got it cleaned up.  I don't want to do any more changes at this time because it is already too big to view here.

**Pull request merged**
