### PR TITLE
Required Centos Perl Modules that were not present

### PR DESCRIPTION
**Pull request by rhiann0n**
Added the following as required by cmake & make:

perl-core
perl-ExtUtils-MakeMaker-Coverage
perl-ExtUtils-MakeMaker
perl-Getopt-Long-Descriptiveperl-DBD-MySQL
perl-LWP-Authen-Negotiate 
gcc-c++

### CODE REVIEW

**Comment by knnniggett** [comment]
Did you know that zoneminder rpms are available from zmrepo?  You don't need to build from source.  

You did not state what version of CentOS you are using.  From the list I'd guess you are using CentOS 7.

The information in Readme.md is accurate for CentOS 6.  While I agree it should be updated, I do not completely agree with your list. 

For a list of the current dependencies look at the rpm specfile here:
https://github.com/ZoneMinder/ZoneMinder/blob/master/distros/redhat/zoneminder.el7.spec

You also removed the line continuations "/" which is not acceptable.

**Comment by rhiann0n** [comment]
I'm using 6.5

**Comment by knnniggett** [comment]
For CentOS 6, look here for the list of dependencies:
https://github.com/ZoneMinder/ZoneMinder/blob/master/distros/redhat/zoneminder.el6.spec

**Comment by knnniggett** [comment]
I've updated the main Readme with a new set of installation instructions, which makes this particular PR no longer relevant.  However, I do need feedback on the new method, particularly how well it flows and how easy it is to understand.  Any questions or comments about the new instructions should be placed into a new issue.

**Pull request closed without merging**
