### PR TITLE
packpack nightly builds

### PR DESCRIPTION
**Pull request by knnniggett**
Initial support for packpack nightly builds. We can't test deployment until after this is merged.

### CODE REVIEW

**Comment by knnniggett** [comment]
Good news. The build made it a lot farther than I expected.
The only thing that failed was my attempt to install the ZoneMinder package into the Travis environment so we can test it.  

Just for reference to myself, here is where it is failing: 
```$ if [ ${OS} == "ubuntu" ] && [ ${DIST} == "trusty" ]; then gdebi --non-interactive build/zoneminder_*amd64.deb; mysql -uzmuser -pzmpass zm < db/test.monitor.sql; sudo zmpkg.pl start; sudo zmfilter.pl -f purgewhenfull; fi
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
Need to be root to install packages
Warning: Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'zmuser'@'localhost' (using password: YES)
sudo: zmpkg.pl: command not found
sudo: zmfilter.pl: command not found```

**Comment by knnniggett** [comment]
Here is the next error message to work on:
```
Preparing to unpack .../zoneminder_0.0.1-1_amd64.deb ...
Unpacking zoneminder (0.0.1-1) ...
dpkg: dependency problems prevent configuration of zoneminder:
 libgnutls26:amd64 (2.12.23-12ubuntu2.5) breaks zoneminder (<= 1.24.4-1) and is installed.
  Version of zoneminder to be configured is 0.0.1-1.

dpkg: error processing package zoneminder (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 zoneminder
```

**Comment by knnniggett** [comment]
Making progress. The Travis build reports success, but there are still some issues to be worked out when we try to install and start zoneminder:
```
Stopping ZoneMinder: Can't open config file '/etc/zm/zm.conf': Permission denied at /usr/share/perl5/ZoneMinder/Config.pm line 129.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 129.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Compilation failed in require at /usr/bin/zmdc.pl line 65.
BEGIN failed--compilation aborted at /usr/bin/zmdc.pl line 65.
Zoneminder already stopped


Database already at version 1.30.2, update aborted.


Freshening configuration in database
Loading config from DB
Saving config to DB
Done Updating, starting ZoneMinder
Starting ZoneMinder: Can't open config file '/etc/zm/zm.conf': Permission denied at /usr/share/perl5/ZoneMinder/Config.pm line 129.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 129.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Compilation failed in require at /usr/bin/zmdc.pl line 65.
BEGIN failed--compilation aborted at /usr/bin/zmdc.pl line 65.
failure

invoke-rc.d: initscript zoneminder, action "start" failed.
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Warning: Using a password on the command line interface can be insecure.
Can't open config file '/etc/zm/zm.conf': Permission denied at /usr/share/perl5/ZoneMinder/Config.pm line 129.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 129.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Compilation failed in require at /usr/bin/zmdc.pl line 65.
BEGIN failed--compilation aborted at /usr/bin/zmdc.pl line 65.


The command "if [ ${OS} == "ubuntu" ] && [ ${DIST} == "trusty" ]; then sudo gdebi --non-interactive build/zoneminder_*amd64.deb; mysql -uzmuser -pzmpass zm < db/test.monitor.sql; sudo /usr/bin/zmpkg.pl start; sudo /usr/bin/zmfilter.pl -f purgewhenfull; fi" exited with 0.
store build cache
```

I'm out of time for today.

**Comment by knnniggett** [comment]
This is currently failing due to a change in packpack
https://github.com/packpack/packpack/issues/59

**Comment by rtsisyk** [comment]
> This is currently failing due to a recent change in packpack
packpack/packpack#59

Fixed, sorry for the regression.

I have a strong interest to fix PackPack for ZoneMinder. Let's try to merge all patches you need into the upstream. I took a look into utils/packpack directory:

1. utils/packpack/pack/rpm.mk

```
--- a/packpack/pack/rpm.mk	2017-01-14 14:01:50.364217882 -0600
+++ b/packpack/pack/rpm.mk	2017-01-14 14:01:19.594985311 -0600
@@ -23,11 +23,13 @@
 		-e 's/Release:\([ ]*\).*/Release: $(RELEASE)%{dist}/' \
 		-e 's/Source0:\([ ]*\).*/Source0: $(TARBALL)/' \
 		-e 's/%setup .*/%setup -q -n $(PRODUCT)-$(VERSION)/' \
+		-e 's/%autosetup -n .*/%autosetup -n $(PRODUCT)-$(VERSION)/' \
 		-i $@.tmp
 	grep -F "Version: $(VERSION)" $@.tmp && \
 		grep -F "Release: $(RELEASE)" $@.tmp && \
 		grep -F "Source0: $(TARBALL)" $@.tmp && \
-		grep -F "%setup -q -n $(PRODUCT)-$(VERSION)" $@.tmp || \
+		(grep -F "%setup -q -n $(PRODUCT)-$(VERSION)" $@.tmp || \
+		grep -F "%autosetup" $@.tmp) || \
 		(echo "Failed to patch RPM spec" && exit 1)
 	@ mv -f $@.tmp $@
 	@echo
```

Fixed by [a pull request](https://github.com/packpack/packpack/pull/55) from @knnniggett.

2. utils/packpack/deb.mk.patch:
```
--- a/packpack/pack/deb.mk	2017-01-15 16:41:32.938418279 -0600
+++ b/packpack/pack/deb.mk	2017-02-16 15:44:43.267900717 -0600
@@ -14,7 +14,7 @@
 DPKG_BUILD:=$(PRODUCT)_$(DEB_VERSION)-$(RELEASE)_$(DPKG_ARCH).build
 DPKG_DSC:=$(PRODUCT)_$(DEB_VERSION)-$(RELEASE).dsc
 DPKG_ORIG_TARBALL:=$(PRODUCT)_$(DEB_VERSION).orig.tar.$(TARBALL_COMPRESSOR)
-DPKG_DEBIAN_TARBALL:=$(PRODUCT)_$(DEB_VERSION)-$(RELEASE).debian.tar.$(TARBALL_COMPRESSOR)
+DPKG_DEBIAN_TARBALL:=$(PRODUCT)_$(DEB_VERSION)-$(RELEASE).tar.$(TARBALL_COMPRESSOR)
 
 # gh-7: Ubuntu/Debian should export DEBIAN_FRONTEND=noninteractive
 export DEBIAN_FRONTEND=noninteractive
```

[Fixed](https://github.com/packpack/packpack/commit/bf7e8737cb6ef055974cc0adbed00f8542a7cf6b)  by me in the upstream.

3. utils/packpack/redhat_package.mk:
```
.PHONY: redhat_package
.NOTPARALLEL: redhat_package

redhat_package: redhat_bootstrap package

redhat_bootstrap:
	sudo yum install -y --nogpgcheck build/zmrepo.noarch.rpm
```

I also suffer from this problem. Any ideas how to implement this feature in the general way? May be  add some ENV variable? I added [an ugly hack](https://github.com/packpack/packpack/blob/39b91f3a3087957915e303fe862f8971bb800d32/pack/rpm.mk#L61-L63) to automatically enable https://packagecloud.io/PACKAGECLOUD_USER/PACKAGECLOUD_REPO repository during the build, but we need a proper solution for that.

**Comment by knnniggett** [comment]
> I also suffer from this problem. Any ideas how to implement this feature in the general way?

@rtsisyk Thanks for the response. At the moment, the current workaround is sufficient for us. In a perfect world, having a way to pass a custom mock/yum config into each redhat-based Docker container would be preferred. However, I don't have much experience working directly with Docker so I don't know how easy or reasonable a request this is. As I continue to work with packpack & Travis, perhaps a better solution will come to me in time.

I am currently working towards getting our packages deployed to our own remote server, and I just learned the hard way that Travis does not call the Deploy step for pull requests. doh! So I am working on finding another way to test that. 

Once I get packages deploying properly, I'm going to revisit the deb package issue we discussed over in your forum and I also figure out a solution to git tag versioning such that packpack generates a package with compatible versioning... If I have to I will just force VERSION each time, I need to spend more time with this to determine if that is really necessary.

And there apparently is an AWS S3 outage affecting Travis, so it doesn't look like I'm going to make more progress on this today.

**Comment by knnniggett** [comment]
Thanks to the suggestion from @rtsisyk I have set the VERSION & RELEASE variables in such a way that packpack now cranks out zoneminder rpms in the same format as can be found in other rpm repos such as fedora & zmrepo, :

`zoneminder-1.30.2-15.fc25.x86_64.rpm`

The same change also cranks out debs which look like this:
`zoneminder_1.30.2-15_amd64.deb`

Note that the 15 represents the number of commits since the last release (tag), and it will keep incrementing with each commit, until it resets back to 1 following another release.

@SteveGilvarry 
@connortechnology 
Please comment on whether this naming convention meets your needs for the deb packages. I can set VERSION & RELEASE to whatever you want if this is not sufficient.

**Comment by connortechnology** [comment]
I have no problem with it, but it does go against debian policy... which basically says that if there is no debian version component, then the upstream version can't have a hyphen.... could we use a + instead?

**Comment by knnniggett** [comment]
> I have no problem with it, but it does go against debian policy... which basically says that if there is no debian version component, then the upstream version can't have a hyphen.... could we use a + instead?

Let's choose something that fits debian policy then. 
What is the debian version component?

I can set the packpack RELEASE var to be {DISTRO}{RELNUM} to match what you've got in your ppa.
e.g. zoneminder_1.30.0-xenial1_amd64.deb

Would that work?

**Comment by connortechnology** [comment]
The xenial part can serve as the debian revision, which then allows us to have hyphens in the upstream version.

I like zoneminder_version+commits-xenial_amd64.deb

**Comment by knnniggett** [comment]
Yeah I can do that. So from the example I posted earlier:
`zoneminder_1.30.2-15_amd64.deb`

becomes

`zoneminder_1.30.2+15-trusty_amd64.deb`

**Comment by knnniggett** [comment]
@connortechnology Look good?
```
Debian packages are ready
-------------------------------------------------------------------
14412 /build/zoneminder-dbg_1.30.2+48-trusty_amd64.deb
 5192 /build/zoneminder-doc_1.30.2+48-trusty_all.deb
   20 /build/zoneminder_1.30.2+48-trusty.debian.tar.xz
    4 /build/zoneminder_1.30.2+48-trusty.dsc
 3464 /build/zoneminder_1.30.2+48-trusty_amd64.build
    4 /build/zoneminder_1.30.2+48-trusty_amd64.changes
 6232 /build/zoneminder_1.30.2+48-trusty_amd64.deb
    0 /build/zoneminder_1.30.2+48.orig.tar.xz
```

**Comment by connortechnology** [comment]
Looks good to me.

**Comment by knnniggett** [comment]
This is ready for merge.

Some things to note about this pr:
- only 64bit packages are built, not 32
- clang support has been removed (would require special debian package scripts ...any volunteers?)
- Thanks to a "feature" of Travis, the deploy script cannot be tested with a pr nor from another fork. Will have to follow up with this after this pr is merged.

**Comment by knnniggett** [comment]
Actually, wait a minute. I just read the packpack very recently merged support for i386 & even arm builds.

**Comment by knnniggett** [comment]
Looks like the only 32bit builds available are for ubuntu trusty & xenial. 

Have to keep an eye out for fedora support:
https://hub.docker.com/u/i386/

I tried arm, but the docker failed with wrong exe format. I'm punting on this. Will save arm builds for another day.

This is PR is ready.

**Comment by SteveGilvarry** [comment]
After this has gone in I will add clang back in as a Travis build but
exclude from packaging, as per Tarantool does it. Would be nice to have
branch support but I think packpack would need a way to upload to a
different repo for each branch and have branch in file name.

**Comment by knnniggett** [comment]
On a side note, since I wrote this so I could test this locally as much as possible, I inadvertently created a distro-agnostic method to follow the same simple steps which generate any package, rpm or deb, of your choosing.... e.g. once this pr is merged and verified to be working well, we might want to consider replacing all our "build package from-source" documentation in readthedocs with a single set of steps which calls startpackpack.sh.

**Comment by rtsisyk** [comment]
> I tried arm, but the docker failed with wrong exe format. I'm punting on this. Will save arm builds for another day.

@knnniggett you need ARM host to build ARM packages. Docker is not qemu, it can't emulate foreign architectures.

**Comment by rtsisyk** [comment]
I have no idea why i386 Fedora and CentOS are not supported on Docker Hub. You can try to add a custom Dockerfile for it to  PackPack, I'll enable it on Docker Hub.

**Pull request merged**
