### PR TITLE
Create CMS.php

### PR DESCRIPTION
**Pull request by amshaikh**
This utility will let the user view multiple monitors synchronously for a selected date. It helps tracing and reviewing any incident on a location.

### CODE REVIEW

**Comment by knnniggett** [comment]
Thank you for taking the time to create this pull request, but it does not currently meet our standards on a number of issues.

Rather than get into the details of what should change in the code just yet, first please provide us a better description of what this looks like. Screenshots would be most helpful here.

I'm particularly interested in knowing/seeing what this does that the following new feature doesn’t already do: https://github.com/ZoneMinder/ZoneMinder/pull/961

**Comment by pliablepixels** [comment]
Gave it a try - nice job. A few notes:

a) There is a larger effort going on here https://github.com/ZoneMinder/ZoneMinder/pull/961 that does what you have done and some more - take a look and see if you want to contribute there

b) Its a better idea to put CMS inside the skins directory so its routed via index.php and security is applied

**Comment by connortechnology** [comment]
I think we should insist on valid html5.

Also I'd like to see a lot of the table structure generated by 1 or 2 lines of code. 

Next parsing directory structure to get the images etc is bad. Once my storage areas code gets integrated there will be object methods to do a lot of the work.  So I see this code changing considerably.

**Comment by knnniggett** [comment]
I'm closing this out since @amshaikh has not responded to our questions.
If that changes then we can reopen this.

**Pull request closed without merging**
