### PR TITLE
Make el6 and el7 build process a little more automated

### PR DESCRIPTION
**Pull request by clipo1979**
This is to make the el6 and el7 build a little more automated with less hard coded variables.

This also fixes a build bug when trying to build on el6 with the following error:

-- Status of cambozola script was:
CMake Error at distros/redhat/CMakeLists.txt:41 (install):
install DIRECTORY given non-directory "zoneminder" to install.

CMake Error at distros/redhat/CMakeLists.txt:42 (install):
install DIRECTORY given non-directory "zoneminder" to install.

further work is still needed to finalise.

There seems to be a problem with the jscalendar and cambozola install directories that has not been resolved with this.

### CODE REVIEW

**Comment by clipo1979** [comment]
Update:
Some configuration missed from initial pull
CMakeFiles.txt in the redhat directory was not fully updated.

**Comment by knnniggett** [comment]
Thank you for taking the time to do this work as most people are not willing. 
If you have just learned github, you did pretty well for the first time.  
In the future, try to do all your work on your local branch, test it, and then just do one commit before you push to your fork.  It would make your pull request much easier to read.  

I need to take more time to look at this, but it looks like you need to add a commit, similar to  0991391, but for the eleseif case of ZM_TARGET_DISTRO STREQUAL "el6"

We also need to stick with the name "zoneminder", not "zm", for the name of the sys v init script.

**Comment by knnniggett** [comment]
Just sent a PR to your repo, which addresses the items I mentioned.
Feel free to comment.

**Comment by knnniggett** [comment]
@clipo1979 Just a reminder that the ball is in your court on this one.  Let me know if you have any questions about the pull request I sent you.

**Comment by clipo1979** [comment]
knnniggett,

Thanks for the comments, I'll take a look and respond over the weekend when I have some spare time.

**Pull request merged**
