### PR TITLE
Don't pass request data as a monitor array to daemonControl

### LINKED ISSUE #1451: Can't enable monitor from the API.
When I make a request to `/zm/api/monitors/1.json` with `{'Monitor[Function]': 'Modect', 'Monitor[Enabled]': 'false'}` I can disable an enabled monitor, however when I try to POST `{'Monitor[Function]': 'Modect', 'Monitor[Enabled]': 'true'}` to a disabled monitor, I can't enable it.

I am running version 1.29.0 under Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by connortechnology**
fixes #1451 I think

### CODE REVIEW

**Comment by connortechnology** [comment]
@pliablepixels thoughts? I can merge this myself if you agree with it

**Comment by pliablepixels** [comment]
@connortechnology  - looks good. If the user did not pass Function= in the POST data, the arguments would never get constructed correctly

**Comment by pliablepixels** [comment]
actually hold on - 5 mins

**Comment by pliablepixels** [comment]
@connortechnology - I'm trying to map it to #1451 

He  wrote

> When I make a request to /zm/api/monitors/1.json with {'Monitor[Function]': 'Modect', 'Monitor[Enabled]': 'false'} I can disable an enabled monitor, however when I try to POST {'Monitor[Function]': 'Modect', 'Monitor[Enabled]': 'true'} to a disabled monitor, I can't enable it.

If he just passed ``'Monitor[Function]': 'Modect', 'Monitor[Enabled]': 'true'`` to  [daemonControl](https://github.com/ZoneMinder/ZoneMinder/blob/api_fixes/web/api/app/Controller/MonitorsController.php#L230) that would [push](https://github.com/ZoneMinder/ZoneMinder/blob/api_fixes/web/api/app/Controller/MonitorsController.php#L252) zmc and zma to daemons and a ``-m $id`` (as no type). The constructed zmdc query should still be right?

**Comment by connortechnology** [comment]
The daemonControl was looking at $monitor[Type] and complaining.  I'm not sure if the code was continuing past the error.

**Comment by pliablepixels** [comment]
Ah gotcha -it would likely throw an exception there is there was no isset check. Looks good then.

**Pull request merged**
