### PR TITLE
Update to CakePHP 2.8.0 copy in lib folder

### PR DESCRIPTION
**Pull request by SteveGilvarry**
Path of least resistance for PHP7, was to move to CakePHP 2.8.0. Was just as simple as replacing the lib folder with the new CakePHP version.
Tested on Ubuntu 14.04 PHP 5.5 confirmed version and monitors json both working fine.
Upgraded to PHP 7, restarted apache, fixed new /etc/php/apache2/php.ini file for correct timezones.
Checked version and monitors json post upgrade and working fine and confirmed using /web/api that I was now running CakePHP 2.8.0.

@knnniggett want to test this on centos 6 to confirm it works with php 5.x on there?

### CODE REVIEW

**Comment by SteveGilvarry** [comment]
Resolves #1291 and #1227

**Comment by knnniggett** [comment]
What do you guys think of the possibility of making CakePHP a submodule?
It would certainly simplify the process of changing to a different version.
Of course, that means we will have nested submodules.

Because the API uses php traits, I can't use the API on CentOS 6.
I've gone ahead and packaged the current versions of cakephp and crud with the rpm, even though the API doesn't work. I guess I'm hopeful that someday we might be able to get some level of usage out of it.

Anyway, because the API does not work on CentOS 6, I'm not sure how I can test a newer version of CakePHP on this distro. Thoughts?

**Comment by SteveGilvarry** [comment]
If you can make a submodule take just one folder of the other project it could work, but then again the next jump to 3 won't just be a swap.

Interesting that it doesn't work as CakePHP is PHP 5.3+ and looks like Centos 6 was 5.3.3. The only thing Cake does is the API so if it doesn't work now then no point trying to test it with an update

**Comment by knnniggett** [comment]
It isn't Cake, but Crud, which uses php traits, which were implemented in php 5.4. The API needs both to work, which means we must follow the most stringent requirements.

**Pull request merged**
