### PR TITLE
Api auth

### PR DESCRIPTION
**Pull request by connortechnology**
Adds auth layer to api.
Currently just denies access if auth is turned on.
Login does not work becase cakephp doesn't not work with mysql's PASSWORD hashes.

### CODE REVIEW

**Comment by knnniggett** [comment]
I think our previous conversation in irc about php crypt applies to this pr.  
I ran the test that @SteveGilvarry suggested on my CentOS 6 platform 
http://www.the-art-of-web.com/php/blowfish-crypt/

CentOS 6 ships with php 5.3.3 and the good news is that the test described in the previous link was successful.  RYPT_BLOWFISH is enabled on CentOS 6.

**Comment by SteveGilvarry** [comment]
An example of changing hash method that I liked. Not sure if we have a way implement the immediate hashing of old passwords in db on upgrade, but at least to change password hash on logon.
https://stackoverflow.com/questions/19955793/migrating-users-table-with-hashed-password-from-old-php-app-to-new-laravel-app

**Comment by connortechnology** [comment]
I will read that now, but a thought that I had was that if we supported both old and new methods for login, then on successful login we could update the password entry to something newer.  I think it needs to be done.  video surveillance is where security is paramount.

**Comment by connortechnology** [comment]
Ooh, I like the double hashing..

**Comment by devinellis** [comment]
- Shouldn't the API be stateless? why are we adding a session cookie?
- Isn't it a json/xml API? Why are we adding html views?
- Doesnt Zoneminder already support some sort of Auth? Can't the API honor that?

**Comment by pliablepixels** [comment]
we should close this PR

**Comment by knnniggett** [comment]
@connortechnology should we close this per @pliablepixels request?

**Pull request closed without merging**
