### PR TITLE
Upgrade bundled jQuery (Closes: #1263)

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by connortechnology** [comment]
Why jquery 1.11.3 when there is a 1.12 available?

**Comment by onlyjob** [comment]
I knew you would ask that. :)
Just being super careful. I've already tried with 1.11.3 because this is the version Debian ship at the moment. Therefore 1.11.3 is much better tested. I'm not maintaining jQuery so I'm not sure what kind of concerns jQuery maintainers may have regarding newer version. However I know from experience that it is better/safer to exercise some caution about latest releases...
We can always upgrade again I suppose...

**Comment by connortechnology** [comment]
Well, I don't think anyone cares, so here it is merged.

**Comment by onlyjob** [comment]
Thank you. :)

**Pull request merged**
