### PR TITLE
Update fr_fr.php

### PR DESCRIPTION
**Pull request by Jypy**

### CODE REVIEW

**Comment by knnniggett** [comment]
@Jypy Thank you for taking the time to update the language file.

**Comment by Jypy** [comment]
You are welcome :)

**Comment by manupap1** [comment]
This update replaces some special characters by bad characters.
This is probably due to a bad file encoding type (it should be UTF-8).

**Comment by Jypy** [comment]
Strange, I had issues with the "original" so I made those changes. Now I have again issues with the update you've made ?!

**Comment by manupap1** [comment]
I have made no update to the file after your changes.

**Comment by Jypy** [comment]
You're totally right! My mistake. I updated to 1.28.1 and I thought the file was changed again. But that was just the original file back :)
I'll change the encoding on mine and see if it fix on your side.

**Comment by Jypy** [comment]
Looks like it's already UTF-8.

**Pull request merged**
