### PR TITLE
Always show ptz

### PR DESCRIPTION
**Pull request by connortechnology**

### CODE REVIEW

**Comment by knnniggett** [comment]
Testing this is still on my to-do list. Recall I have a camera which requires 256 presets (long story).
I don't envision this pr will work well with that, but let me try it and see what it looks like. Perhaps I can come up with an alternative.

**Comment by connortechnology** [comment]
I have one that doesn't have presets, and the result is a little silly too.  We need some smart design in here.

**Comment by SteveGilvarry** [comment]
No PTZ here so will need to wait for @knnniggett to get back from holidays.

**Comment by knnniggett** [comment]
Since we tend to agree that we should implement a different solution, shall I close this?

**Comment by connortechnology** [comment]
I don't see any need to close it. We need to do the work to come to a solution. Now that we are back in development more we can do so. I will take another look and think about it.

**Comment by knnniggett** [comment]
I have used some surveillance software which, after hovering over a particular corner, will superimpose semi-transparant ptz controls onto the view. Thought that was cool.

**Comment by connortechnology** [comment]
I like that. However I think right now clicking on the image zooms in.

**Comment by knnniggett** [comment]
Right, but if the ptz controls are overlayed on top of the image, would that not cause zoneminder to call the onclick function associated with ptz control instead, assuming the "click" occurred over a ptz control widget?

**Comment by knnniggett** [comment]
I'm going to close this simply for organizational purposes. I think we have all agreed that we want to do something different than what this pr does. Let's create a new pr when someone has time to revisit this in the future.

**Pull request closed without merging**
