### PR TITLE
ubuntu 15.04

### PR DESCRIPTION
**Pull request by seeebek**
Added changes for building and running on Ubuntu 15.04 which now uses systemd and has ffmpeg in main repository.

### CODE REVIEW

**Comment by seeebek** [comment]
Not ready to merge. I still get "Can't symlink '1' to 'Monitor-1': Permission denied"

**Comment by knnniggett** [comment]
That sounds like a file permission problem.  Make sure your packaging scripts are setting up the events folder with the owner and group set to www-data.

You might also want to make sure there aren't any leftover symlinks in this folder from prior build attempts.

**Comment by seeebek** [comment]
Yep, that's the problem. Events folder and few others were set to root. Thanks for your help. 
I will try to get the script to set them to www-data.

**Comment by seeebek** [comment]
I found the problem and I addressed it in #840 . I don't know the decisions made behind the problematic parts of the code and I will wait until @connortechnology has a look on it.

**Comment by seeebek** [comment]
It was a false alarm. Apparently I broke something on the way. On a clean try it works. You are welcome to review it and merge.

**Comment by knnniggett** [comment]
@connortechnology I'm hoping you can take a look at this and merge if you think it is good to go.

**Pull request merged**
