### PR TITLE
Start monitors when show page after hidden on Montage page

### PR DESCRIPTION
**Pull request by IgorA100**
Correction to #4053

### CODE REVIEW

**Comment by connortechnology** [comment]
check latest master.  Should actually kill the stream.

**Comment by IgorA100** [comment]
Fantastic !

Everything works correctly :)
Now, if the Montage page is not displayed in the browser, then the load on the server CPU is significantly reduced.

**Comment by IgorA100** [comment]
Probably the same should be applied to the Watch page?

**Comment by connortechnology** [comment]
Yes definitely apply to watch.  And zones and zone edit.   Maybe it should be automatic in MonitorStream.js.  
Need to also pause rtsp2web. I think janus is already handled.

**Comment by IgorA100** [comment]
> Yes definitely apply to watch. And zones and zone edit.

Done

> Maybe it should be automatic in MonitorStream.js.

Yes, it worked!

> Need to also pause rtsp2web.

I haven't figured out rtsp2web yet :( 

> I think janus is already handled.

I installed Janus, but I don't like how it works at all and I haven't figured it out yet.

**Pull request merged**
