### PR TITLE
Update et_ee.php

### PR DESCRIPTION
**Pull request by hanzese**
Translation update.

### CODE REVIEW

**Comment by connortechnology** [comment]
Looks good to me.

**Comment by knnniggett** [comment]
Is this PR still valid?  
There are 29 merge conflicts that need to be manually resolved before this can be merged.  

You can view et_ee.php with the conflicts highlighted here:
https://gist.github.com/knnniggett/04754bc400ae6a293bd0

The start of each conflict is indicated by `<<<<<<< HEAD`

@hanzese Can you fix these?

**Comment by knnniggett** [comment]
Closing due to merge conflicts.  @hanzese If you ever have an opportunity to resolve the conflicts, feel free to send a new pull request.

**Comment by hanzese** [comment]
i'm back... The link above not working? 29 conflicts?

**Pull request closed without merging**
