### PR TITLE
Camera reboot function

### PR DESCRIPTION
**Pull request by cnighswonger**
Dahua cameras support a "Reboot" function. Other's may as well. This series of commits adds a reboot function option to the camera control configuration as well as a reboot button to the control UI.

### CODE REVIEW

**Comment by knight-of-ni** [comment]
After building master today, I see the following in my logs:
```
2019-03-30 10:20:03	web_php		16643	WAR	Unknown function call Monitor->CanReboot from /usr/share/zoneminder/www/skins/classic/includes/control_functions.php:359	includes/Monitor.php	279
```

Doing some initial troubleshooting, this PR appears to be missing a zm_update-1.33.x.sql file to insert the CanReboot column into an existing database. We also need to define CanReboot in Monitor.php, perhaps here: https://github.com/ZoneMinder/zoneminder/blob/master/web/includes/Monitor.php#L116

@cnighswonger would you mind send a new PR to correct this? Looks like we will need to bump the version of zm to 1.33.5 for existing systems to capture this change.

**Comment by cnighswonger** [comment]
> @cnighswonger would you mind send a new PR to correct this? Looks like we will need to bump the version of zm to 1.33.5 for existing systems to capture this change.

I'll take care of this first of next week. Thanks!

**Comment by connortechnology** [comment]
I already took care of it.

**Comment by cnighswonger** [comment]
Thanks. I've had a few scheduling issues the past week or so which have kept me away from the dev box.

**Comment by knight-of-ni** [comment]
I am hit or miss myself with a new job so I completely understand. We are always interested in people who wish to hang around and participate in the project.

**Pull request merged**
