### PR TITLE
Add libjwt as a optional library

### PR DESCRIPTION
**Pull request by hax0kartik**
Hey, this should *theoretically* fix issue #2810 
However, I could not test my changes, it will be awesome if someone is able to verify that these changes indeed do work as intended.

### CODE REVIEW

**Comment by hax0kartik** [comment]
Build is failing due to a unrelated linting error.

**Comment by pliablepixels** [comment]
Hi, I'm not the right person to review this - someone with familiarity of debian's requirements should test this and I'd recommend you test your code too.

**Comment by hax0kartik** [comment]
I have no idea on how to build this. Would copying the steps from travis.yml be enough?

**Comment by connortechnology** [comment]
Here are the commands that I use, and which match what our debian package builds use.
cmake -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_SKIP_RPATH=ON \
  -DCMAKE_VERBOSE_MAKEFILE=OFF \
  -DCMAKE_COLOR_MAKEFILE=ON \
  -DZM_RUNDIR=/var/run/zm \
  -DZM_SOCKDIR=/var/run/zm \
  -DZM_TMPDIR=/var/tmp/zm \
  -DZM_LOGDIR=/var/log/zm \
  -DZM_WEBDIR=/usr/share/zoneminder/www \
  -DZM_CONTENTDIR=/var/cache/zoneminder \
  -DZM_CGIDIR=/usr/lib/zoneminder/cgi-bin \
  -DZM_CACHEDIR=/var/cache/zoneminder/cache \
  -DZM_WEB_USER=www-data \
  -DZM_WEB_GROUP=www-data \
  -DCMAKE_INSTALL_SYSCONFDIR=etc/zm \
  -DZM_CONFIG_DIR=/etc/zm \
  -DCMAKE_BUILD_TYPE=Debug

make && sudo make install

**Comment by hax0kartik** [comment]
@connortechnology Hey, thanks for the steps, it seems to build correctly now.

**Comment by hax0kartik** [comment]
@connortechnology I just tested my changes and they seem to work fine, requesting code review.

**Pull request merged**
