### PR TITLE
Port to OmniOS/Solaris

### PR DESCRIPTION
**Pull request by whorfin**
Before things drift too much further out of sync [I notice changes already since 1.28.1 involving
proliferation of SYS_gettid calls and rollback of nonportable pthread join], I wanted to get this out there.
I need to do further testing against this latest master, but this set of patches is running on 1.28.1
for some time.  [see issue #756 for announcement]

### CODE REVIEW

**Comment by knnniggett** [comment]
It is always interesting to see what kind of systems zoneminder has made its way onto.  

@whorfin Looks we need to work through some of these before this can be merged.  Some just are not right at all and would break ZoneMinder for the rest of us.  

Lastly, we have a long term goal to remove autotools, and eventually switch completely over to cmake.  That should be the next item on the agenda.

**Comment by knnniggett** [comment]
I tell you what, let's do this in cmake. 
It looks like cmake is not checking the host_os like autotools is, so I need to add that. 
Just so I get it right, what exactly is the result of "uname -s" on your system?
In the meantime, can you modify this pull request, or generate a new one, that includes just the changes your configure.ac, the .cpp files, and .h files?  Once we get that far, then we can tackle to stuff with ZM_VERSION.

**Comment by whorfin** [comment]
OK!
Push reversions and rollbacks as requested.

uname -s produces
SunOS
under OmniOS [and presumably most solarian devi
You're absolutely right about PATH, my issue with zmupdate was the usage of mysqldump, which
lives in /opt/local/bin with pkgin.  A quick grep shows a bazillion references to mysqldump in
various incorrect locations which won't work, like a hardcoded /usr/bin reference in zmeventdump.
So yes please, let's fix this more rigorously via path detection in cmake and proper referencing in
all the locations that call the various mysql.* utilities.

**Comment by DanTheColoradan** [comment]
@whorfin :+1:  nice work.

**Comment by knnniggett** [comment]
I'm in an off site training class the rest of this week so my zoneminder productivity is going to be low.  Go ahead and create an issue that tracks the remaining issues with Solaris.

**Comment by whorfin** [comment]
Excellent, thanks!
My zoneminder productivity is also going to plummet as the millions of other things to tend to jump the line.
I will however create an obvious-looking issue with Solaris issues as I encounter them.

**Comment by knnniggett** [comment]
@whorfin Now that #844 is merged, try building zoneminder with cmake.  Start with these steps:
```bash
cmake /
	-DZM_WEBDIR="/opt/local/share/httpd/htdocs/zm" /
	-DZM_CGIDIR="/opt/local/libexec/cgi-bin" /
	-DZM_WEB_USER="www" /
	-DZM_WEB_GROUP="www" /
.
make
```
Don't forget the dot "." and don't add any additional parameters unless it does not build.
You can see all the parameters one can send to cmake here:
https://github.com/ZoneMinder/ZoneMinder/blob/master/CMakeLists.txt

Each time you re-run cmake, delete the cache file from the previous attempt: CMakeCache.txt

My guess is you will run into issues.  If that happens, create a new github issue, and post your entire build output and the entire cmake command you used to start the process.

**Comment by whorfin** [comment]
Rather than just complaining, I've attempted to create a patch set which resolves the [so far] issues
It is #851

**Comment by knnniggett** [comment]
You should undo all the changes to .gitignore.  .gitignore is global, so we can't add references that exclude files simply on the grounds that it they are not used for *your* distro when they are needed for *other* distros.  It does not hurt anything to have those files lying around.

Did you make the changes to the cmake modules yourself, or did you get them from some other source?
The modules under cmake/Modules are canned, and they should be kept that way.  Troubleshooting custom changes to the modules would make things more difficult than it should be.  

We need to accomplish what you are trying to do within the CmakeList.txt files, or adding additional modules (or replacing them entirely is ok), as long are they come from a reputable source that has tested the modules.  

For example, does your system have access to a Solaris version of FindPolkit.cmake module?  We could check for Solaris in CMakeLists.txt and then call that module instead of the one already there .....Or, if we can verify the canned module is cross-platform then we could use that.

**Comment by connortechnology** [comment]
Most of this looks fine.  I would prefer to find a replacement to get the thread id instead of just not doing it, but I'm ok with it for now.

**Pull request merged**
