### PR TITLE
Debian Distro Folder

### PR DESCRIPTION
**Pull request by SteveGilvarry**
Some work I did a while back when I was not sure which distro folder to build from, so thought pulling official debian one in might help us and them. Not invested in any of this, but we should try to refine down to a single folder per distro. I removed some of the changes to replacement packages as I was building on Ubuntu and some of the packages in Debian unstable are not in Ubuntu. So Cake and Moo are still from master in this instance.

### CODE REVIEW

**Comment by onlyjob** [comment]
I'm against idea of maintaining Debian packaging upstream.
Not only it is a duplication of effort but there are also so many problems...

I think it is a disservice to Debian users when different packages are available from official Debian repositories and from upstream. Some users will be inevitably confused which packages to use.

With all due respect to ZoneMinder developers, they will always lack incentive to follow/answer Debian bug reports and meet Debian standards and policy requirements.

There is no better proof of harm than recent situation with Zoneminder when the latter was removed from Debian because nobody was looking after Zoneminder packages in Debian while three people contributed to Debian packaging within Zoneminder. Why look after Debian packaging without incentive to have it in Debian? Would you let official Debian package to rot once again? If you are caring about Debian package then you are doing it in wrong place.

Here is relevant quote of two Debian Developers discussing where is the
best to maintain Debian package -- upstream and/or in Debian:

>> If the packaging folder stays until the package reaches Debian, that's
>> fine. However, if it stays after that, it's bad to have it upstream,
>> even if it's not conflicting with our workflow. Why? Well, simply
>> because instead of a single place where to contribute to the packaging,
>> you now have 2: one upstream, and one in Debian. Once one or the other
>> gets updated, who's going to do the work of propagating the change in
>> the other place where the packaging information is stored? What's the
>> point of having double the work to update the debian folder in both
>> Debian and upstream? Just get that done in Debian, and that's it...
>
> I see no motivation on the upstream site to follow different Debian
>revisions, closing bugs in the debian/changelog etc.  Thus a single
>place of maintenance is best maintained in a repository controlled by
>Debian...

  * https://lists.debian.org/20150610062931.GB15148@an3as.eu

In fact I've never seen proper upstream Debian packaging in any project.
The following link explains problems that are affecting ZoneMinder as well -- a fascinating summary expressed even better than I could do it:

  * https://www.zabbix.org/wiki/Appeal_against_public_upstream_packaging

And here is another example of similar problems is Zabbix packages for Debian -- plain and miserable: https://support.zabbix.com/browse/ZBX-7996

So please, pretty please, focus on improving ZoneMinder and work on Debian packaging only within Debian. I shall be happy to provide any hints and assistance.

P.S. ZoneMinder is now available for "Jessie" through [official backports](http://backports.debian.org/) and this is yet another reason to stop wasting time on maintaining forks of Debian package outside of Debian.

**Comment by SteveGilvarry** [comment]
@onlyjob I would have been cool with first 2 lines, you are much more versed in the ways of debian than me. So thank you for explaining your view in detail. This was more for building during development process as I had been building ZoneMinder from source and was looking to move to packages as every one was saying we should. And the debian folder we had in upstream was not usable.
Could you recommend a process for development builds/packages that doesn't conflict with debian package? I have done some searching but couldn't find anything good for upstream devs.
https://github.com/ZoneMinder/ZoneMinder#debian is what we have now.

**Comment by onlyjob** [comment]
No worries. :) Maybe https://wiki.debian.org/UpstreamGuide could be of use.
Typically if you need to (re-)build Zoneminder on Debian you can either `apt get source zoneminder` or `debcheckout zoneminder` (provided that you have `devscripts` package installed) then build it using "pdebuild" or "debuild". I'm not sure what kind of problem you are trying to address but if necessary we can prepare a staging package and upload it to "experimental" if there is something to stabilise before uploading to "unstable".

I welcome any help and I believe that Zoneminder packaging would benefit from team maintenance. I don't want to do everything alone. ;)

I will be happy to review your patches and apply 'em on your behalf if you send your improvements to me. It will be nice if you can create an account on [Alioth](https://alioth.debian.org/projects/collab-maint/) (unless you already have one).
Maybe we can invite Emmanuel Papin too as he was working on `distros/debian8`...

**Comment by onlyjob** [comment]
I've forgotten to mention command to fetch build dependencies: `apt-get build-dep zoneminder`...

**Comment by knnniggett** [comment]
Along the lines of what @SteveGilvarry said, we are providing the scripts in our source tree to provide a method for those who wish to build zoneminder for development related reasons.  It is not intended to replace what you are doing. We still want the typical Debian user to get zoneminder from the Debian base repo.

The long term goal is to change the mindsets of our large user base to get away from building-from-source.  The idea is to automate the build process as much as we can, which should cut down on the number of build issues created in our forums, and thus allow us to focus on responding to real issues with the product.

@onlyjob I like your suggestion of checking out the official Debian based zoneminder.  I hadn't heard of that capability.  What would be nice is if someone knowledgeable in Debian packaging could write up a guide on how to build master using this method, and then update Readme.md with those instructions.

Would we be able to do something similar on the Ubuntu side with @connortechnology 's PPA?

**Comment by SteveGilvarry** [comment]
@knnniggett thanks for explaining my quick response better, if we can get a process sorted for packaging with upstream sources and document it then I see no reason to keep debian folders.
@onlyjob option 3 here https://www.zabbix.org/wiki/Docs/howto/rebuild_debs would that be the appropriate process? But in my case it would even be doing the same from my git repo not even from an upstream tarball. I will keep searching and am happy to document it once I can get a working process.

**Comment by onlyjob** [comment]
Thanks @SteveGilvarry, thanks @knnniggett. :)

The problem with "debian" directory in source tree is that maintaining it and merging with [collab-maint ZoneMminder repository](http://anonscm.debian.org/cgit/collab-maint/zoneminder.git) is a maintenance burden. At some point differences accumulate and documentation becomes ambiguous because there is more than one single Debian packaging diverged from each other. When official package is well maintained one can argue that `debian` directory in source tree becomes unnecessary...

If ZoneMinder documentation mention where to find Debian package (maybe a [PTS](https://tracker.debian.org/pkg/zoneminder) page) then there will be no question about which packaging is authoritative and hopefully contributors won't be confused  where to direct their efforts.

Unlike some other Debian package repositories, I keep ZoneMinder package repository de-coupled from ZoneMinder sources. It is basically just a `debian` directory so checkout is lightweight and fast. Re-building master is a matter of adding `debian` directory on top of ZoneMinder sources and using command like `debuild -us -uc -b` to build it.
Debian packaging is focused on (latest) release so to rebuild "master" one can remove or disable patches by editing `debian/patches/series` file. Applying patches can be done with `quilt [push|pop]` command. Here is a page about "quilt": https://wiki.debian.org/UsingQuilt

Regarding Ubuntu, I believe usually there is no need to do anything special as they leach everything we do in Debian. Strangely enough, according to PTS page Ubuntu  still have ZoneMinder 1.26.5 so it seems that they branched of from old Debian package at some point. I'm not sure how it works in Ubuntu but I know that most Debian packages end up in Ubuntu sooner or later.

When Ubuntu synchronise ZoneMinder with Debian, PPA may become unnecessary. Having said that I'm not sure what is the primary purpose of ZoneMinder PPA -- for rapid deployment of fixes to ZoneMinder users in Ubuntu or as authoritative/official ZoneMinder  repository for Ubuntu. Debian practices encourage contribution to single official repository without PPA-like fragmentation.

I've never seen Zabbix "rebuild_debs" page before but something like this can work for us, perhaps with fewer details... Here is a generic page about Debian packaging: https://wiki.debian.org/HowToPackageForDebian

**Comment by SteveGilvarry** [comment]
So something like this, based on what we currently have in the readme? Note I will go play around with this, just validating my thought process of cloning zm and debian collabmaint and bring together to make a folder ready for package creation. Dependency install is before this section in the readme.

root@host:~# git clone https://github.com/ZoneMinder/ZoneMinder.git zoneminder;
root@host:~# git clone https://anonscm.debian.org/git/collab-maint/zoneminder.git debian;
root@host:~# cd zoneminder;
root@host:~# ln -s ../debian;
root@host:~# debuild -us -uc -b;

**Comment by connortechnology** [comment]
So first off, we have these build directories because debian was dropping us.  Even though you have taken up packaging zm in debian, we reserve the right to offer different options for development.  For example, how we have split up the packaging so that you don't have to install ALL of Zm.  Debian traditionally have not made themselves party to the development teams' conversations regarding direction.  Maybe that is changed now.

I have made it my responsibility for follow debian bug reports, and it is in everyone's interest to solve all bugs from all distributions. 

Ubuntu PPA is required to provide newer versions of ZM for older Ubuntu releases.  

Similarly our efforts to provide packages for debian are to provide newer version for older debian releases, or any situation where debian is not interested in providing what we want to provide, which will almost always be niche projects.

**Comment by onlyjob** [comment]
@connortechnology,

> So first off, we have these build directories because debian was dropping us.

ZoneMinder was dropped from Debian because of lack of maintenance. Too many bugs and no maintainers. I believe that to some extent it happened also because packaging efforts were misdirected away from Debian. I've never seen your bug reports requesting sponsorship (i.e. upload) or uploads to [mentors](http://mentors.debian.net/)...

> Even though you have taken up packaging zm in debian, we reserve the right to offer different options for development.

No objections. :)

> For example, how we have split up the packaging so that you don't have to install ALL of Zm.

I'm not sure I understand what do you mean by this...

> Debian traditionally have not made themselves party to the development teams' conversations regarding direction. Maybe that is changed now.

Again, I'm not sure what do you mean. Working with upstream is in Debian policy for quite a while. But if there are no maintainers working on the package then there are nobody to liaison in upstream matters... Lack of time may be the case as well...

> I have made it my responsibility for follow debian bug reports, and it is in everyone's interest to solve all bugs from all distributions.

Fantastic. Very good. :)

> Similarly our efforts to provide packages for debian are to provide newer version for older debian releases,

This is where you should be careful about how to do things. [Debian backports](http://backports.debian.org/) is a best place to provide newer versions of software for older Debian releases.
If you can't do it through official backports then please do not provide packages for older Debian versions at all.

Packages for "Jessie" are already there. As for Wheezy I doubt it needs latest ZoneMinder at all.

> or any situation where debian is not interested in providing what we want to provide, which will almost always be niche projects.

Let's provide what you want to provide properly. Unlike PPA that tolerates bad habits I believe we're all want packages compliant with policy and  best practice. Please work with Debian, don't isolate your efforts (it didn't work too well in the past).

It will be very nice indeed to avoid confusing Debian users with different packages that need different installation instructions -- you may have already noticed that official package may initialise database in a different way, etc.

Please let me know if you need any help in Debian packaging or if there is anything you'd like to include to official package.

**Comment by connortechnology** [comment]
ZoneMinder was unmaintained.  Then we took it over.  I tried for a year to take over maintainership and work with Peter Howard and others to get newer versions in.  Then it was kicked. This is just a minor point because it sounds like you are blaming us.  You probably aren't, but someone else reading might think so.

Debian has never forwarded anything to the ZoneMinder devs until you came along.  Granted before we took over, there really wasn't anyone to forward bugs to...

Since you are doing such a good job, I am perfectly happy to sign off on removing debian build scripts from the zm source tree.  It does kindof go against what we have been trying to do though.

I hear you on backports... that hadn't occurred to me.  It should have.

As to wheezy, lots of people will prefer to run wheezy due to systemd.  Also, lots of raspberry pi's will still run wheezy as people don't feel the need to upgrade.  There is no reason for them to be stuck on old ZM.  Old ZM just wasn't that good.  We still have a long way to go.

The thing about the not having to install all of ZM: so, traditionally the zoneminder package just installs all of zm.  If you look in our debian8 folder you will see the wonderful work done by @manupap1 splitting it up so that you don't have to install all the UI's or even any ui.  Or the db.   There is even a libzoneminder-perl package for people who want to use our code in other apps.  This is the future of zoneminder.

**Comment by connortechnology** [comment]
Just also wanted to mention that I'm really happy to have you taking over the debian side of things.  I was trying to do what I could, but the learning curve is steep and there is a lot of other things to do.   I appreciate your efforts.

**Comment by onlyjob** [comment]
>ZoneMinder was unmaintained. Then we took it over.

That's understandable.

> I tried for a year to take over maintainership and work with Peter Howard and others to get newer versions in. Then it was kicked.

I had no idea, sorry. We (Debian) should never let it happen. We are doing our best to make contribution easier but when people have something to contribute their work can be noticed only if there are bug reports, NMUs, sponsorship requests etc.
Usually it is not too difficult to take over unmaintained package... I've adopted some packages even before I became uploading developer.

> This is just a minor point because it sounds like you are blaming us. You probably aren't, but someone else reading might think so.

Of course I'm not blaming. My point is that packaging is best done downstream to relieve upstream developers from packaging duties so they could focus on improving software and therefore use their time more effectively.

> Debian has never forwarded anything to the ZoneMinder devs until you came along. 

I see... 

>Granted before we took over, there really wasn't anyone to forward bugs to...

Hopefully we can improve that. As for forwarding bugs it is a matter of approach. In case of isolated fix, attach your patch to bug report and announce  intention to prepare an upload (NMU). Upload your source package to _mentors.debian.net_ and file a bug report against "sponsorship-requests" pseudo-package to notify prospective sponsors. Someone will come back to you. In case when one of the maintainers have uploading rights it is even easier.

> Since you are doing such a good job, 

Thank you for your kind words. :)

>I am perfectly happy to sign off on removing debian build scripts from the zm source tree. It does kindof go against what we have been trying to do though.

I don't insist on removing but if you have any doubts then let's see how it works in the long term. If some months later I won't be able to convince you that Debian packaging is best done on the Debian side then I doubt I would have any better arguments than what I have now...

> I hear you on backports... that hadn't occurred to me. It should have.

Thank you, thank you. :)

> As to wheezy, lots of people will prefer to run wheezy due to systemd.

I'm not sure how do you count them... In any case _Jessie_ can be used with _SysV_ (and it is rather easy) and _systemd_ is only used by default. Besides all major GNU/Linux distros already gave up to _systemd_. I do not want to encourage users of soon-to-become unsupported _Wheezy_ to avoid upgrading their system by offering them up-to-date software. One of the Debian strengths (unavailable to CentOS users) is ability to upgrade to current release.  I reckon we could offer commercial/paid LTS for Wheezy as maintaining software for several releases is a significant burden.

> Also, lots of raspberry pi's will still run wheezy as people don't feel the need to upgrade. There is no reason for them to be stuck on old ZM. Old ZM just wasn't that good. We still have a long way to go.

I reckon I could make a backport for Wheezy but I can't test it due to limited time unless someone would be interested to offer some funding... If you want to make such backport I might be able to upload it for you but I can't make any promises regarding time frame...

> The thing about the not having to install all of ZM: so, traditionally the zoneminder package just installs all of zm. If you look in our debian8 folder you will see the wonderful work done by @manupap1 splitting it up so that you don't have to install all the UI's or even any ui. Or the db. There is even a libzoneminder-perl package for people who want to use our code in other apps. This is the future of zoneminder.

IMHO it is a bit sad that @manupap1 done this work without attempting to bring his efforts to Debian or intention to (co-)maintain Debian package...
I've considered splitting ZoneMinder into more packages but I have some doubts about it so it would be nice if we discuss it a little bit... _libzoneminder-perl_ (commented in official packaging) is in line with policy but apart from Zoneminder itself I'm not aware of any software that could depend on ZoneMinder Perl module.
Splitting of _libzoneminder-perl_ may be a good idea eventually but I'm not sure if it would be immediately useful. Everything is ready for shipping modules in _libzoneminder-perl_ and this is just a matter of approval.

Separating UI could be a good idea but it always needs arch-any CGI scripts so it seems that there will be more binary packages that (almost) always installed together hence greater maintenance burden for little benefit.
IMHO separate packages for UI skins is not a good idea due to additional package index overhead while UI skins packages are very small and best shipped together.
It could be nice to separate arch-dependent (arch-any) and arch-independent (arch-all) binaries but for ZoneMinder difference is not too big especially if CakePHP (accountable for the most arch-independent part of ZoneMinder) is shipped in standalone binary package.

> @onlyjob Just also wanted to mention that I'm really happy to have you taking over the debian side of things. I was trying to do what I could, but the learning curve is steep and there is a lot of other things to do. I appreciate your efforts.
Oh, and I also appreciate @SteveGilvarry and everyone else too.

Thank you very much. :) A real pleasure to read it.
I shall be happy to help if you ever want to become more involved into Debian matters.

From my side I must say that you guys are a fantastic team -- one of the best upstreams I had a honour to work with. Thank you sincerely for your work. :)

> Aren't I full of love this morning?

;)

**Comment by manupap1** [comment]
@onlyjob
I have done this work as a short term effort and it was clear before starting it that I would not take a maintainer responsibility (https://github.com/ZoneMinder/ZoneMinder/pull/596).
It’s a pity that we could not have this discussion late last year, such situations happen with open source collaborative work.
But the key is that we can have the discussion now, especially with a competent person as you.
Originally, the package’s splitting has been discussed with @connortechnology (https://github.com/ZoneMinder/ZoneMinder/pull/605):
- _libzoneminder-perl_ for people who want to write their own interface.
- _zoneminder-database_ to install the database either locally or remotely. This package can also be used standalone to install the database on an offline server.
- _zoneminder-core_ to install binaries and scripts for background process. I noted that a multi-server implementation is underway, I don’t know the details but maybe this will give more value to a main package without ui files.
- _zoneminder-ui-*_ to install ui files. For these files, the splitting is questionable. The benefit is low and the majority of users will install zoneminder by using the metapackage (which install all ui packages) without paying attention to the splitting.

Another important point is that I included the support of debconf and dbconfig to assist users during installation, reconfiguration and removal:
- database configuration with replacement of default passwords (some people use ZM over internet so this hardening is not an option) 
- webserver configuration (currently only apache)
- prompt for files deletion when removing the package

I would appreciate if all or parts of this work could be included in the official packages. I would be happy to help you if you need. Please tell me.

**Comment by SteveGilvarry** [comment]
FYI on ubuntu I am starting the process to get debian package pulled in, it is stuck due to Ubuntu patches. Did a bzr merge and all the patches were no longer required or in debian package. So that led me back to making a sync request. https://bugs.launchpad.net/ubuntu/+source/zoneminder/+bug/1482109
Just need to add a build log from pbuilder-dist now and hopefully we can get 1.28.1 in wily.

**Comment by SteveGilvarry** [comment]
@onlyjob @connortechnology FYI https://launchpad.net/ubuntu/+source/zoneminder/1.28.1-7 Benefits of having a maintained debian package. Now to start cleaning up the bugs in launchpad

**Comment by onlyjob** [comment]
Hi @manupap1,

> libzoneminder-perl for people who want to write their own interface.

I've introduced (commented) "libzoneminder-perl" but for now I'm holding back this change as I know no packages that could benefit from shipping modules separately...

Eventually (when convenient) we can introduce "libzoneminder-perl" but for now it seems to be not too important...

> zoneminder-database to install the database either locally or remotely. This package can also be used standalone to install the database on an offline server.

This is unnecessary. Official Debian package do not use debconf to configure database hence database configuration can be done (manually) from where ZoneMinder is installed. I think shipping separate database package will complicate database upgrades etc. Besides DB package is very small and DB upgrade scripts belong to main ZoneMinder package anyway...

> zoneminder-core to install binaries and scripts for background process. I noted that a multi-server implementation is underway, I don’t know the details but maybe this will give more value to a main package without ui files.

As I mentioned earlier I believe it makes the most sense to separate _arch-any_ and _arch-all_ packages. However Zoneminder UI is not exclusively _arch-all_ (like it would be if UI were 100% PHP). Since CGI scripts are _arch_any_ UI will always need both packages. I already reduced weight of UI component by using external CakePHP package... Also I want to avoid maintenance overhead from such separation...

> zoneminder-ui-* to install ui files. For these files, the splitting is questionable. The benefit is low and the majority of users will install zoneminder by using the metapackage (which install all ui packages) without paying attention to the splitting.

Splitting skins into multiple small packages introduces unnecessary overhead to maintenance and to repository indexes without any apparent benefits. I believe it might be nice to ship all skins in one package if we manage to separate UI elegantly...

> Another important point is that I included the support of debconf and dbconfig to assist users during installation, reconfiguration and removal:
    database configuration with replacement of default passwords (some people use ZM over internet so this hardening is not an option)
    webserver configuration (currently only apache)
    prompt for files deletion when removing the package

There are many reasons to avoid using debconf unless when it is absolutely necessary. Debconf high priority messages are disruptive and being frown upon; debconf introduces non-negligible maintenance overhead not just to package maintainer but to translators as well. Debconf can not configure remote database so we leave this to user (as documented in README.Debian). _Apache2_ configuration is handled by `dh_apache2` (debconf is deprecated for such purpose) and _nginx_ configuration can be handled manually with instructions from README.Debian).
I believe that introducing debconf merely to confirm cleanup on package purge is not worth the effort. There are not that many legitimate use cases for Debconf and usually it is hard to avoid Debconf misuse...

> I would appreciate if all or parts of this work could be included in the official packages. I would be happy to help you if you need. Please tell me.

Thank you. I think we already have most of worthy improvements of yours. Please let me know if there is anything that I've missed.

**Comment by manupap1** [comment]
@onlyjob
I know debconf is subject to controversy regarding issues you mentioned and I understand that from a maintainer's point of view there is no arguments in favor.
My goal was to offer the possibility for users to have a working ZM installation without having to perform multiple operations on the command line, similarly to phpMyAdmin's package which use debconf and dbconfig.

**Comment by onlyjob** [comment]
I understand your intention. :) We actually tried this approach in some packages and found it limited and problematic in many regards. I believe to certain extent lack of semi-automatic configuration can be compensated by clear and straightforward installation instructions in `README.Debian`. It is not that hard to manually invoke few commands to set-up a database but it allows a lot more flexibility than it would be ever possibly within boundaries imposed by debconf limitations...

**Comment by connortechnology** [comment]
Hey @onlyjob just a little thing to note: your package build uses the libav-tools versions of libavcodec and friends.  My understanding is that debian has decided to switch to the ffmpeg versions, and those are now available in debian.  

We decided to use the ffmpeg versions a while back in providing packages. You might wish to as well.

**Comment by onlyjob** [comment]
Of course, @connortechnology. The plan is to wait till `1.28.1-8` migrate to "testing, do (hopefully last) upload to "jessie-backports" and then switch entirely to "ffmpeg" in "unstable".

**Comment by onlyjob** [comment]
Partially switch to "ffmpeg" already happened since those -dev libraries in Build-Depends are now provided by "ffmpeg". The only things left to do is apparently to drop "libav_path.patch" and replace "libav-tools" with "ffmpeg". I've just [committed such change](https://anonscm.debian.org/cgit/collab-maint/zoneminder.git/commit/?id=611f5891532a6b6387f7e592a6b2cdc6390d9907). It will go live with next upload.

**Pull request closed without merging**
