### PR TITLE
fixed wrong doc root

### PR DESCRIPTION
**Pull request by zhuykovkb**
Fixed wrong DocumentRoot in apache vhost

### CODE REVIEW

**Comment by zhuykovkb** [comment]
Hello, DocumentRoot doesn't exist!

```
ubuntu@vm-kzhuykov:~/dev/ZoneMinder$ docker exec -it zoneminder_zm_1 ls -l /var/www
total 4
drwxr-xr-x 2 root root 4096 Aug  6 13:37 html
ubuntu@vm-kzhuykov:~/dev/ZoneMinder$
```

**Comment by zhuykovkb** [comment]
Also, when run building container i got:


Step 18 : RUN "/ZoneMinder/utils/docker/setup.sh"
 ---> Running in 9d7a62f6ec06
160807 13:40:12 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
160807 13:40:12 mysqld_safe Logging to '/var/log/mysql/error.log'.
160807 13:40:12 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
mysqladmin: connect to server at 'localhost' failed
**AH00112: Warning: DocumentRoot [/var/www/zm] does not exist**
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
Enabling module cgi.
To activate the new configuration, you need to run:
  service apache2 restart
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
160807 13:40:27 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
 ---> 9ae123de114e
Removing intermediate container 9d7a62f6ec06
Step 19 : CMD /ZoneMinder/utils/docker/start.sh
 ---> Running in 5f9d63c8e368
 ---> 9860ababb37c
Removing intermediate container 5f9d63c8e368
Successfully built 9860ababb37c
ubuntu@vm-kzhuykov:~/dev/ZoneMinder$

**Comment by zhuykovkb** [comment]
@connortechnology can u help with merge this?:)

**Comment by knnniggett** [comment]
I'm going to invoke the "touched it last" rule and poke @hamiltont 
He changed that part back in April of 2014 wiht commit f2dbb1f . Since we know plenty of others have successfully been using the docker container, it would stand to reason there is more to the story.

**Comment by zhuykovkb** [comment]
also, in Dockerfile we have a mention for '/usr/local/share/zoneminder':

```
ubuntu@vm-kzhuykov:~/dev/ZMT$ grep www-data Dockerfile | grep -v ^#
RUN chown -R www-data:www-data /usr/local/share/zoneminder/
ubuntu@vm-kzhuykov:~/dev/ZMT$
```

as chown by `www-data` user. As we know, it's for Apache2.

```
ubuntu@vm-kzhuykov:~/dev/ZoneMinder$ docker-enter zoneminder_zm_1
root@a7b7e01a8002:/# grep -r www-data /etc/apache2/
/etc/apache2/envvars:export APACHE_RUN_USER=www-data
/etc/apache2/envvars:export APACHE_RUN_GROUP=www-data
root@a7b7e01a8002:/#
```

**Pull request merged**
