### PR TITLE
fix scoring based on max value of zone, rather than area of entire zone

### PR DESCRIPTION
**Pull request by vajonam**
#1781 fixes for adjusting scoring algorithm based on largest allowable size

### CODE REVIEW

**Comment by vajonam** [comment]
make sure we fall back to size of the zone polygon if max_* is 0

**Comment by connortechnology** [comment]
My mind breaks down while looking at this code/logic.  It is going to take some serious looks by several people to agree on this.  

@mastertheknife ?

**Comment by vajonam** [comment]
Agreed, but my point is that if you specify a max size for your alarmed area, you % or scre should be calculated against that max size, because if the alarmed area greater than the max size it will be ignored.

**Comment by mastertheknife** [comment]
On my system, sometimes the score is really low, its 1 some events.
There were times it was less than 1, but a fix in the code (exists since 1.26 or so) makes sure the minimum is 1. The fix in the current code is like a band aid, perhaps we should really improve the scoring algorithm.
I haven't had time to understand the changes in this PR and its effect on the score. Its better to go safe and slow with this, its a significant change that will affect all users.

**Comment by knnniggett** [comment]
Looks like this issue needs some follow up.
Assigning a milestone of 1.31.0 to this.

**Comment by vajonam** [comment]
I am curious to see how many users actually use score for anything?

**Pull request closed without merging**
