### PR TITLE
Api improvements

### PR DESCRIPTION
**Pull request by connortechnology**
This simplifies the configuration of the API by pulling the db connection info from zm.conf.

### CODE REVIEW

**Comment by josh4trunks** [comment]
Any idea where I can put this code to split ZM_DB_HOST?
I realized I couldn't put it in the class, so maybe we need a function somewhere that can be called first?

```
        if (strpos(ZM_DB_HOST, ':')) {
                // Host variable may carry a port or socket.
                list($host, $portOrSocket) = explode(':', ZM_DB_HOST, 2);
                        if (is_numeric($portOrSocket)) {
                                $port = $portOrSocket;
                        } else {
                                $socket = $portOrSocket;
                        }
        } else {
                $host = ZM_DB_HOST;
        }
```

**Comment by josh4trunks** [comment]
PR for API is here.
https://github.com/connortechnology/ZoneMinder/pull/1

This is ready for testing / merge.

**Comment by SteveGilvarry** [comment]
@connortechnology checkout @josh4trunks changes and merge to your repo if you want them in this one, or let me know to let this one in as is.

**Comment by josh4trunks** [comment]
Another PR to fix my earlier whitespace mistake
https://github.com/connortechnology/ZoneMinder/pull/2

**Comment by knnniggett** [comment]
Seems to work with a default build (default zmuser, zmpass, sql port).

Note that this will require an API documentation update to specify it is no longer necessary to manually populate custom mysql credentials into the database.php file. Other than the README for Fedora & CentOS, I don't know where that documentation is.

**Comment by josh4trunks** [comment]
=]
sweet, more automation

**Comment by connortechnology** [comment]
I think this also means this file doesn't have to have cmake substitutions...

**Comment by tendonut** [comment]
You might want to update this doc to reflect this convenient change.
https://media.readthedocs.org/pdf/zoneminder/latest/zoneminder.pdf

It still suggests that the db user/pass is stored in api/app/Config/database.php.

**Comment by josh4trunks** [comment]
How do we update the documentation? As of April 20, 2017 the PDF @tendonut linked is still outdated.

* For the section "Changed Default DB User", point 2 can be deleted entirely.
* Also in the section "New installs", in point 7, this statement can be deleted.
`Additionally, you must also edit /usr/share/zoneminder/www/api/app/Config/database.php in a similar manner on each
ZoneMinder Server. Scroll down and change login and password to the values you created in the previous step.`

**Comment by knnniggett** [comment]
If you are referring to our readtehdocs documentation, there should be a link "Edit on Github" at the top right of the page, which will take you to proper file to edit under this folder:
https://github.com/ZoneMinder/ZoneMinder/tree/master/docs

**Comment by josh4trunks** [comment]
@knnniggett sounds good, I made the changes I mentioned and will submit a PR.

I'm thinking I'll also add a note to zm.conf of the possible formats of ZM_DB_HOST, mentioned here.
https://github.com/ZoneMinder/ZoneMinder/pull/1498#issue-156160173

**Pull request merged**
