### PR TITLE
Iconnor updated console

### PR DESCRIPTION
**Pull request by connortechnology**
deprecate all the sequence calculations.  They are overly complex.

### CODE REVIEW

**Comment by knnniggett** [comment]
I'm not sure I understand the purpose of this pr, or perhaps I just don't see how this makes things any less complex. Typically I'd rather not change things that have been previously working, unless we have a really good reason. Not ruling out that there isn't something I just don't understand or overlooked in all the commits. Maybe we can discuss this one at our next Monday night meeting and/or get some other opinions on this one. @kylejohnson @SteveGilvarry

**Comment by connortechnology** [comment]
This was a bunch of fixes for @kylejohnson 's old updated console.  I hadn't deleted it so that he could reference it, but he never did.  It can be deleted.

**Comment by knnniggett** [comment]
Ah, okay. I was going crazy trying to make sense of this one.

**Comment by connortechnology** [comment]
There is some good stuff in there but should be done separately.  I want to get rid of the up and down arrows everntually anyways.

**Pull request closed without merging**
