### PR TITLE
remove autotools builds, replace them with cmake versions

### PR DESCRIPTION
**Pull request by connortechnology**
pretty straight forward.  Removed the dirs that used autotools and renamed the cmake ones to remove confusion. Or create it.

### CODE REVIEW

**Comment by axklim** [comment]
<pre>
gudik@sa-pc128:/data/work/zoneminder/zm$ export LANG=C
gudik@sa-pc128:/data/work/zoneminder/zm$ sudo dpkg-buildpackage
dpkg-buildpackage: source package zoneminder
dpkg-buildpackage: source version 1.28.108-nmu2015100101
dpkg-buildpackage: source changed by Isaac Connor <iconnor@connortechnology.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build zm
 debian/rules clean
dh clean --buildsystem=cmake --parallel
   dh_testdir -O--buildsystem=cmake -O--parallel
   dh_auto_clean -O--buildsystem=cmake -O--parallel
   dh_clean -O--buildsystem=cmake -O--parallel
 dpkg-source -b zm
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format `1.0'
dpkg-source: warning: source directory 'zm' is not <sourcepackage>-<upstreamversion> 'zoneminder-1.28.108'
dpkg-source: info: building zoneminder in zoneminder_1.28.108-nmu2015100101.tar.gz
dpkg-source: info: building zoneminder in zoneminder_1.28.108-nmu2015100101.dsc
 debian/rules build
dh build --buildsystem=cmake --parallel
   dh_testdir -O--buildsystem=cmake -O--parallel
   debian/rules override_dh_auto_configure
make[1]: Entering directory `/data/work/zoneminder/zm'
dh_auto_configure -- \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_SKIP_RPATH=ON \
		-DCMAKE_VERBOSE_MAKEFILE=OFF \
		-DCMAKE_COLOR_MAKEFILE=ON \
		-DZM_RUNDIR=/var/run/zm \
		-DZM_SOCKDIR=/var/run/zm \
		-DZM_TMPDIR=/var/tmp/zm \
		-DZM_LOGDIR=/var/log/zm \
		-DZM_WEBDIR=/usr/share/zoneminder/www \
		-DZM_CONTENTDIR=/var/cache/zoneminder \
		-DZM_CGIDIR=/usr/lib/zoneminder/cgi-bin \
		-DZM_WEB_USER=www-data \
		-DZM_WEB_GROUP=www-data \
		-DCMAKE_INSTALL_SYSCONFDIR=etc/zm
-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:13 (message):
  The git submodules are not available.  Please run

  git submodule update --init --recursive


-- Performing Test HAVE_SENDFILE4_SUPPORT
-- Performing Test HAVE_SENDFILE4_SUPPORT - Success
-- Sendfile support: Linux/Solaris sendfile()
-- Looking for libv4l1-videodev.h
-- Looking for libv4l1-videodev.h - found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for backtrace_symbols
-- Looking for backtrace_symbols - found
-- Looking for ucontext.h
-- Looking for ucontext.h - found
-- Looking for sys/sendfile.h
-- Looking for sys/sendfile.h - found
-- Looking for sys/syscall.h
-- Looking for sys/syscall.h - found
-- Looking for syscall
-- Looking for syscall - found
-- Looking for sendfile
-- Looking for sendfile - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of siginfo_t
-- Check size of siginfo_t - done
-- Check size of ucontext_t
-- Check size of ucontext_t - done
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.7") 
-- Looking for zlib.h
-- Looking for zlib.h - found
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.26.0") 
-- Looking for curl/curl.h
-- Looking for curl/curl.h - found
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Looking for include files stdio.h, jpeglib.h
-- Looking for include files stdio.h, jpeglib.h - found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1e") 
-- Looking for openssl/md5.h
-- Looking for openssl/md5.h - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pcre.h
-- Looking for pcre.h - found
-- Looking for gcrypt.h
-- Looking for gcrypt.h - found
-- Looking for gnutls/openssl.h
-- Looking for gnutls/openssl.h - found
-- Looking for gnutls/gnutls.h
-- Looking for gnutls/gnutls.h - found
-- Looking for mysql/mysql.h
-- Looking for mysql/mysql.h - found
-- Looking for libavformat/avformat.h
-- Looking for libavformat/avformat.h - found
-- Looking for libavcodec/avcodec.h
-- Looking for libavcodec/avcodec.h - found
-- Looking for libavdevice/avdevice.h
-- Looking for libavdevice/avdevice.h - found
-- Looking for libavutil/avutil.h
-- Looking for libavutil/avutil.h - found
-- Looking for libavutil/mathematics.h
-- Looking for libavutil/mathematics.h - found
-- Looking for libswscale/swscale.h
-- Looking for libswscale/swscale.h - found
-- Looking for vlc/vlc.h
-- Looking for vlc/vlc.h - found
-- Checking prototype MD5 for HAVE_MD5_OPENSSL - True
-- Checking prototype MD5 for HAVE_MD5_GNUTLS - True
-- Checking prototype gnutls_fingerprint for HAVE_DECL_GNUTLS_FINGERPRINT - True
-- Found Perl: /usr/bin/perl (found version "5.14.2") 
-- Checking for perl module Sys::Syslog
-- Checking for perl module Sys::Syslog - found at /usr/lib/perl/5.14/Sys/Syslog.pm
-- Checking for perl module DBI
-- Checking for perl module DBI - found at /usr/lib/perl5/DBI.pm
-- Checking for perl module DBD::mysql
-- Checking for perl module DBD::mysql - found at /usr/lib/perl5/DBD/mysql.pm
-- Checking for perl module Getopt::Long
-- Checking for perl module Getopt::Long - found at /usr/share/perl/5.14/Getopt/Long.pm
-- Checking for perl module Time::HiRes
-- Checking for perl module Time::HiRes - found at /usr/lib/perl/5.14/Time/HiRes.pm
-- Checking for perl module Date::Manip
-- Checking for perl module Date::Manip - found at /usr/share/perl5/Date/Manip.pm
-- Checking for perl module LWP::UserAgent
-- Checking for perl module LWP::UserAgent - found at /usr/share/perl5/LWP/UserAgent.pm
-- Checking for perl module ExtUtils::MakeMaker
-- Checking for perl module ExtUtils::MakeMaker - found at /usr/share/perl/5.14/ExtUtils/MakeMaker.pm
-- Checking for perl module Sys::Mmap
-- Checking for perl module Sys::Mmap - found at /usr/lib/perl5/Sys/Mmap.pm
-- Found PerlModules: TRUE  
-- Using web user: www-data
-- Using web group: www-data
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'polkit-gobject-1;polkit'
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.32.4
-- Found GLIB2: /usr/lib/x86_64-linux-gnu/libglib-2.0.so  
-- Found Polkit: /usr/lib/x86_64-linux-gnu/libpolkit-gobject-1.so  
-- Using mootools core file: mootools-core-1.4.5-compat.js
-- Using mootools more file: mootools-more-1.5.1.js
-- Optional libraries found: zlib cURL OpenSSL PCRE GCrypt GnuTLS AVFormat AVCodec AVDevice AVUtil SWScale libVLC
-- Optional libraries not found:
-- Running ZoneMinder configuration generator
Generating 'src/zm_config_defines.h'
Updating 'db/zm_create.sql'
-- ZoneMinder configuration generator completed successfully
-- Configuring incomplete, errors occurred!
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -DCMAKE_COLOR_MAKEFILE=ON -DZM_RUNDIR=/var/run/zm -DZM_SOCKDIR=/var/run/zm -DZM_TMPDIR=/var/tmp/zm -DZM_LOGDIR=/var/log/zm -DZM_WEBDIR=/usr/share/zoneminder/www -DZM_CONTENTDIR=/var/cache/zoneminder -DZM_CGIDIR=/usr/lib/zoneminder/cgi-bin -DZM_WEB_USER=www-data -DZM_WEB_GROUP=www-data -DCMAKE_INSTALL_SYSCONFDIR=etc/zm returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory `/data/work/zoneminder/zm'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

</pre>

**Comment by knnniggett** [comment]
I'm about as far as I can help with a Debian based build and will let others suggest how to resolve this.

However, on a side note, I will suggest the possibility to create a Debain and/or Ubuntu specific ZM_TARGET_DISTRO in our CMakeLists.txt file which would set all these for you:
```
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_SKIP_RPATH=ON \
        -DCMAKE_VERBOSE_MAKEFILE=OFF \
        -DCMAKE_COLOR_MAKEFILE=ON \
        -DZM_RUNDIR=/var/run/zm \
        -DZM_SOCKDIR=/var/run/zm \
        -DZM_TMPDIR=/var/tmp/zm \
        -DZM_LOGDIR=/var/log/zm \
        -DZM_WEBDIR=/usr/share/zoneminder/www \
        -DZM_CONTENTDIR=/var/cache/zoneminder \
        -DZM_CGIDIR=/usr/lib/zoneminder/cgi-bin \
        -DZM_WEB_USER=www-data \
        -DZM_WEB_GROUP=www-data \
        -DCMAKE_INSTALL_SYSCONFDIR=etc/zm
```

We don't have to do it this way, but the advantage is these parameters would be managed all in one single place, rather then in every control file we have ever created.

**Comment by connortechnology** [comment]
he needs to do git submodule update --init --recursive

**Comment by knnniggett** [comment]
Oh right, I forget the cmake continues processing when it hits that error:
```
CMake Error at CMakeLists.txt:13 (message):
  The git submodules are not available.  Please run

  git submodule update --init --recursive
```

**Comment by axklim** [comment]
try again and:
<pre>
make[2]: Leaving directory `/data/work/zoneminder/zm/obj-x86_64-linux-gnu'
install -D -m 0644 debian/apache.conf  debian/tmp/etc/zm/apache.conf
rm debian/tmp/usr/share/zoneminder/api/lib/Cake/LICENSE.txt
rm: cannot remove `debian/tmp/usr/share/zoneminder/api/lib/Cake/LICENSE.txt': No such file or directory
make[1]: *** [override_dh_auto_install] Error 1
make[1]: Leaving directory `/data/work/zoneminder/zm'
make: *** [binary] Error 2
</pre>

I added in distros/debian/rules :
override_dh_auto_install:
	dh_auto_install --buildsystem=cmake
	install -D -m 0644 debian/apache.conf  $(INSTDIR)/etc/zm/apache.conf
	rm **-f** $(INSTDIR)/usr/share/zoneminder/api/lib/Cake/LICENSE.txt
	rm **-f** $(INSTDIR)/usr/share/zoneminder/api/.gitignore
	rm -r**f** $(INSTDIR)/usr/share/zoneminder/api/lib/Cake/Test

**Comment by connortechnology** [comment]
I wonder why those files aren't there... I guess adding the -f is ok.  Anyone else have an opinion? @onlyjob

**Comment by connortechnology** [comment]
Why are we deleting the license anyways?

**Comment by SteveGilvarry** [comment]
Duplicate license file, they like just one file that covers all licenses. I do wonder if the previous run had already removed the files.

**Pull request merged**
