### PR TITLE
Add support for IPv6 in RTSP code

### PR DESCRIPTION
**Pull request by schrorg**
Monitors with source type 'remote' can now be accessed over IPv6 when using the ZoneMinder RTSP code. This patch uses getaddrinfo(3) now instead of gethostbyname(3) - and changes a lot of networking stuff which **should be tested thoroughly**.

This PR addresses #1151. I would consider marking it **not ready for merge** until other some people tested and reviewed it.

### CODE REVIEW

**Comment by cmcgriff** [comment]
Shouldn't [zm_sdp.cpp](https://github.com/ZoneMinder/ZoneMinder/blob/master/src/zm_sdp.cpp#L115) be updated to handle "IP6" as well.  Currently have an issue with my Hikvision camera where it responds with "IP6" and it throws an exception.

**Comment by connortechnology** [comment]
This looks pretty good to me.  Yes, sdp.cpp should probably be updated as well.

**Comment by schrorg** [comment]
Okay... there seems to be an issue with our cameras then. They are IPv6-only and work like a charm with this PR. Seems to need a deeper look into the connection. If I find the time, I will dive into it again on the weekend.

**Comment by connortechnology** [comment]
@cmcgriff what model is your Hikvision camera?

**Comment by cmcgriff** [comment]
DS-2CD2032F-I and DS-2CD2042WD-I

**Comment by schrorg** [comment]
All of my test cameras return IP4 in SDP address type, so I could not really test what happens if a camera returns IP6. :-/
@cmcgriff, does the last push fix the problem for you?

**Comment by cmcgriff** [comment]
Unfortunately I don't have a good setup to build/test with right now.

Looking at your change it appears to match the change that is suggested in the [Trendnet Wiki](https://wiki.zoneminder.com/Trendnet) for the TV-IP310PI using RTSP.

**Comment by schrorg** [comment]
Cool, I didn't see this! I use a lot of Vivotek cameras and they all do IPv6 with no problem but say "IP4" in the SDP connection. That was the reason for the missing code change.

So we'll wait until someone tested it with a matching camera...

**Comment by schrorg** [comment]
Although I am sure, this code works well, I would like to have it tested by some more people. So I would suggest to remove the label and merge the code into master.

**Comment by knnniggett** [comment]
I'm onboard with this. My only concern is timing. We plan to create a 1.30 release candidate on Monday, and then release 1 week later. I'd suggest we merge this, following the creation of the 1.30 release candidate,

**Comment by schrorg** [comment]
@knnniggett Okay, better merge after the 1.30 release. :-)

**Comment by josh4trunks** [comment]
The change in `src/zm_sdp.cpp` also fixes "Remote" streaming for my Hikvision 2032 camera.
Otherwise I get the `Invalid SDP address type 'IP6' in connection info 'IN IP6 ::'` error

**Comment by connortechnology** [comment]
Screw it, this code needs to be in here, and who knows when the next release will be.

Merged.

**Pull request merged**
