### PR TITLE
Fix 1720

### PR DESCRIPTION
**Pull request by connortechnology**
fix for #1720

### CODE REVIEW

**Comment by knnniggett** [comment]
Shouldn't we also bump the version file to 1.30.2?

**Comment by connortechnology** [comment]
crap, yes of course.

**Comment by connortechnology** [comment]
the question becomes though... are we going to leave this for 1.30.2... or should we in fact merge this db update script to the one that does 1.30.1.. or.. .something else.

**Comment by knnniggett** [comment]
Let's call the next release 1.30.2.
We know there are already some users in the wild running 1.30.1 master so in order to ensure they get the update in this pr, lets bump to 1.30.2.

**Pull request merged**
