### PR TITLE
Use the 3.0 branch of crud, compatible with cakephp 2.x

### PR DESCRIPTION
**Pull request by kylejohnson**
The master branch of crud doesn't support cakephp 2.x.  The 3.0 branch does.

### CODE REVIEW

**Comment by kylejohnson** [comment]
@pliablepixels Please review.

**Comment by pliablepixels** [comment]
@kylejohnson - looks good. Looks like master was updated after @knnniggett configured the gitmodule and ~3.0 is what we need today

**Comment by knnniggett** [comment]
I forget what version of crud I last set the git submodule to, but I recall there was some compatibility issue with upgrading further.

**Comment by pliablepixels** [comment]
The compatibility issue was pulling crud~4.0 which only works with cake 3.0 was it not?

**Comment by knnniggett** [comment]
Actually, I'm not sure what this commit does exactly. 

Previously, I set the git submodule to commit c3976f1 of crud, which translates to version 3.0.10:
https://github.com/ZoneMinder/ZoneMinder/tree/master/web/api/app/Plugin

**Comment by pliablepixels** [comment]
I think this PR is specifying the 3.0 branch right inside gitmodule which is probably easier to understand/maintain  going forward  but given you specified a particular commit inside the plugin directory I wonder why that did not work for @kylejohnson

**Pull request merged**
