### PR TITLE
must call zmMemInvalidate before next

### PR DESCRIPTION
**Pull request by connortechnology**
Also removed the initial zmMemInvalidate.  On each pass in this loop, $monitor will be a fresh hash generated by DBI, so calling it here is useless.

The Memory routines store all their info in the $monitor hash, instead of storing internally.  So we must make sure we clean up before doing a next.

### CODE REVIEW

**Comment by knnniggett** [comment]
I'll test this when I have a moment, but we do need a solution that address zmtrigger (and likley zmx10) as well. It is actually easier to duplicate the mmap file issue with zmtrigger since that runs continuously, compared to zmwatch.

**Comment by connortechnology** [comment]
Are we sure that zmtrigger.pl and zmx10.pl actually have this issue?

**Comment by knnniggett** [comment]
Unfortunately, this pr doesn't fix the issue, and I'm a little surprised you reopened it. As I stated in #1713, this issue is even easier to demonstrate in zmtrigger. I have no way to demonstrate the issue in x10, but I suspect it does since it is similar to the other 2 perl scripts.

I really think the best way to bang this out is is through video conference so we can talk about our ideas before we create another pr. Why don't we make this the primary topic for next Monday's meeting? Are you going be around? I can meet earlier Monday evening if that works for you.

**Comment by connortechnology** [comment]
Have you tested it?  This PR may not fix the issue entirely, but does address 2 problems that could be the cause.  With this PR I do not see the issue.  

Can we discuss the steps required to reproduce this with zmtrigger.pl?  So that others can play too...

Step 1: Have everything running, including zmtrigger.pl
Step 2: restart zmc
Step 3: use something like lsof | grep DEL | grep zm to show the deleted but still existing mmap file?

**Comment by knnniggett** [comment]
Yes, do that. I simply hit the save button on any monitor to restart zmc. If zmtrigger is running, you'll notice the issue immediately (unlike zmwatch which only runs every 5 minutes). 

I suspect that zmMemKey($monitor) is returning false even though there is a file handle still open, which would explain why zmMemInvalidate has been ineffective. I simply have not had the time to dig into this.

**Comment by connortechnology** [comment]
I believe I have found the problem.  What happens is that zmMemVerify mmap's the file which exists, but is zero sized.  Since we were doing if(!zmMemVerify()) next;  that mmap was being left open.  So anywhere we call zmMemVerify, if it fails, we need to call zmMemInvalidate.

**Comment by knnniggett** [comment]
This still doesn't work for me.

State of /dev/shm just after starting zoneminder:
```
[abauer@vFedora25 redhat]$ sudo lsof /dev/shm
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1002/gvfs
      Output information may be incomplete.
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
gnome-she  1120 abauer  mem    REG   0,19 67108904  23435 /dev/shm/pulse-shm-2490409585
gnome-she  1120 abauer  mem    REG   0,19 67108904  20247 /dev/shm/pulse-shm-1608164346
pulseaudi  1161 abauer  mem    REG   0,19 67108904  23462 /dev/shm/pulse-shm-3252086055
pulseaudi  1161 abauer  mem    REG   0,19 67108904  23435 /dev/shm/pulse-shm-2490409585
pulseaudi  1161 abauer  mem    REG   0,19 67108904  20247 /dev/shm/pulse-shm-1608164346
pulseaudi  1161 abauer  mem    REG   0,19 67108904  20228 /dev/shm/pulse-shm-4152841739
gnome-set  1313 abauer  mem    REG   0,19 67108904  23462 /dev/shm/pulse-shm-3252086055
zmc       16044 apache  mem    REG   0,19 61441760 108430 /dev/shm/zm.mmap.2
zmc       16044 apache    3u   REG   0,19 61441760 108430 /dev/shm/zm.mmap.2
zma       16057 apache  mem    REG   0,19 61441760 108430 /dev/shm/zm.mmap.2
zma       16057 apache    3u   REG   0,19 61441760 108430 /dev/shm/zm.mmap.2
zmtrigger 16067 apache  mem    REG   0,19 61441760 108430 /dev/shm/zm.mmap.2
zmtrigger 16067 apache    8u   REG   0,19 61441760 108430 /dev/shm/zm.mmap.2
```

State of zoneminder after opening monitor #2 and hitting save:
```
[abauer@vFedora25 redhat]$ sudo lsof /dev/shm
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1002/gvfs
      Output information may be incomplete.
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF   NODE NAME
gnome-she  1120 abauer  mem    REG   0,19 67108904  23435 /dev/shm/pulse-shm-2490409585
gnome-she  1120 abauer  mem    REG   0,19 67108904  20247 /dev/shm/pulse-shm-1608164346
pulseaudi  1161 abauer  mem    REG   0,19 67108904  23462 /dev/shm/pulse-shm-3252086055
pulseaudi  1161 abauer  mem    REG   0,19 67108904  23435 /dev/shm/pulse-shm-2490409585
pulseaudi  1161 abauer  mem    REG   0,19 67108904  20247 /dev/shm/pulse-shm-1608164346
pulseaudi  1161 abauer  mem    REG   0,19 67108904  20228 /dev/shm/pulse-shm-4152841739
gnome-set  1313 abauer  mem    REG   0,19 67108904  23462 /dev/shm/pulse-shm-3252086055
zmtrigger 16067 apache  DEL    REG   0,19          108430 /dev/shm/zm.mmap.2
zmtrigger 16067 apache    8u   REG   0,19 61441760 108430 /dev/shm/zm.mmap.2 (deleted)
zmc       16143 apache  mem    REG   0,19 61441760 114308 /dev/shm/zm.mmap.2
zmc       16143 apache    3u   REG   0,19 61441760 114308 /dev/shm/zm.mmap.2
zma       16145 apache  mem    REG   0,19 61441760 114308 /dev/shm/zm.mmap.2
zma       16145 apache    3u   REG   0,19 61441760 114308 /dev/shm/zm.mmap.2
```
As you can see zmtrigger is still holding the old mmap file open.

**Comment by connortechnology** [comment]
So here is my analysis. I thought I had this fixed because for the purposes of testing I reduced the monitor reload time.  my zmtrigger releases that mmap file when it reloads the monitors.  The default though is 5 minutes, so it would normally take 5 minutes.

Now in the main loop there, we do a zmMemVerify, but zmMemVerify caches it's results and so basically does nothing.

I propose we remove the caching. I can't see how a couple of reads from the mmap is so slow that we need to cache it.  

Something I am seeing that is weird is this: here is my lsof output.  I have 5 monitors active.

root@pseudo:~# lsof /dev/shm | grep zmt
zmtrigger 21521     root  DEL    REG   0,19             13 /dev/shm/zm.mmap.16
zmtrigger 21521     root  DEL    REG   0,19             22 /dev/shm/zm.mmap.15
zmtrigger 21521     root  DEL    REG   0,19             23 /dev/shm/zm.mmap.11
zmtrigger 21521     root  DEL    REG   0,19             27 /dev/shm/zm.mmap.2
zmtrigger 21521     root  DEL    REG   0,19             14 /dev/shm/zm.mmap.1
zmtrigger 21521     root    8u   REG   0,19  46085872   13 /dev/shm/zm.mmap.16 (deleted)

See that last line, you have it too.  It is different than for the other monitors.  It shows that it isn't an mmap, it is just an open file for read/write.  I'm going to try to figure out where it is coming from.

**Comment by connortechnology** [comment]
Ok. So each mmap uses a file handle, and since we are using MMAP  instead of something like $MMAP as the filehandle it is getting re-used I guess.  Seems weird. I wonder if we should be closing the file handle after mmap'ing it.  Seems unlikely.  

I tested closing the filehandle after mmap'ing it.  The mmap appears to continue to work.  I think you would need the filehandle if you wanted to do locking on it, which it seems likely that somebody would want to do.  
So... close it and free up a filehandle.... or store it properly and be able to do locking.... I'm leaning towards the latter.

**Comment by connortechnology** [comment]
So I've been running without the caching... and  I notice NO performance difference.  Load and CPU usage for zmtrigger is the same as with.  Might be different for shmem... but have pretty much deprecated that...

**Comment by knnniggett** [comment]
speaking of shmem... lets call the code exterminator.... @SteveGilvarry !

**Comment by knnniggett** [comment]
Initial tests indicate this is working. Zmtrigger is no longer holding open the file handle.
While I am optimistic this has been solved for all three: zmtrigger, zmwatch, x10, I do want to let this run a bit longer to verify that zmwatch is fixed too just so I can say I really did test and verify it.

**Comment by knnniggett** [comment]
looks good.

**Pull request merged**
