### PR TITLE
898 is running states

### PR DESCRIPTION
**Pull request by pliablepixels**
1) Updated zmpkg to update new IsActive column of states. If the user is switching to a custom state, IsActive for that state will be 1. If the user is not switching to a custom state (restart/stop/start) then IsActive will be 0 for all

2) Modified create DB script to add the new column

3) Modified updated DB script to update the new column

4) Modified console.php to reflect custom state new (convenience only). If the current state is just Running then nothing will show. This is only done in classic --> does not apply to mobile/xml

reference: https://github.com/ZoneMinder/ZoneMinder/issues/898

### CODE REVIEW

**Comment by pliablepixels** [comment]
@knnniggett not sure why events API PR is also showing here. It was on a different branch and there is already a PR for that.

**Comment by knnniggett** [comment]
Just thinking out loud here:
- Should add a row, called default, that becomes the active state if one if not already specified?
- I noticed that, existing behaviour prior to this pr, is to poll the State table each time zmpkg.pl is called.  I wonder if we can make this more efficient.  I'm not sure we need to do that.  Thinking we only need to check the state table if zmpkg.pl is called with the "start", "state", and possible the "restart" parameter.

**Comment by pliablepixels** [comment]
@knnniggett the issue that I see is that we then have to exclude "default" as a possible run state to display or switch to. I think zmpkg and the php code basically assume each entry in the DB is a valid custom state and then also adds the standard "start" "stop" "restart" (www/skins/classic/views/state.php:54)

Given that state change is infrequent, I wonder if this optimization would help.

**Comment by connortechnology** [comment]
I don't have a problem with how this is implemented.  I wonder if the table will accurately represent the state... or if it will get out of sync easily.  I guess we can address that later. 

As to default state... no I don't think we need an extra row for it...

**Comment by connortechnology** [comment]
we may need to add Starting Up and Shutting down states....

**Comment by pliablepixels** [comment]
@connortechnology what situations do you think may put this table out of sync?
I've handled the following situation:

a) When ZM starts, stops or restarts, zmpkg.pl resets all states to 0
b) When ZM switches to a custom state, zmpkg.pl resets all states to 0 then marks the currrent state as 1

In the event ZM crashes, and starts again, a) will apply

I could not find any part of the code that does not use zmpkg to change state or start/restart

**Comment by knnniggett** [comment]
Hmmm... don't we want a selected custom state to survive a reboot/restart of the server/zoneminder?  Maybe I misunderstood, but I thought that was why were writing which state was active to the dB, rather than just storing it in a global variable.

**Comment by connortechnology** [comment]
The other thing is multi-server.  Each server can be in it's own state. So this might not be the place to put this.  I need to finish up my multi-server patches so that we can store the state in the server table.

**Comment by knnniggett** [comment]
I'll manually merge this over the weekend.

**Comment by knnniggett** [comment]
Merged.  Note that I think we should look into adding the ability to retain the custom state it is in after a reboot.

**Comment by pliablepixels** [comment]
@knnniggett, so let's talk about the reboot state retain part a little more:

a) state = "my_state", user does a "stop" and after a while "start" --> what should the state be - "running" or "my_state"
b) state = "my_state" user does a "restart" --> what should state be "running"  or "my_state"
c) state = "my_state", ZM crashes/machine reboots/etc --> I can understand state could be "my_state"

I am unclear when ZM should really preserve old state and when it should just go back to 'running'

The problem is zmkpg "start" is used to start ZM (restart or first start) --> how do we discern whether that means keep old state or not depending on what may have caused "zmpkg start"

**Pull request merged**
