### PR TITLE
Remove zmc -r argument as it does not seem to be implemented.

### PR DESCRIPTION
**Pull request by SteveGilvarry**
#1340 bought this up and I believe it is correct -r is not implemented.

### CODE REVIEW

**Comment by connortechnology** [comment]
I kinda wonder if we shouldn't either implement it, or be even more aggressive and remove all the other options.  I kinda think the zmc should only take a monitor Id.

**Comment by mastertheknife** [comment]
> I kinda wonder if we shouldn't either implement it, or be even more aggressive and remove all the other options. I kinda think the zmc should only take a monitor Id.

Please don't do that. Local cameras take -d parameter:
`[kfir@atom ~]$ ps ax | grep zmc
 1963 ?        S     80:23 /usr/local/bin/zmc -d /dev/video0
 1984 ?        S     81:18 /usr/local/bin/zmc -d /dev/video1
 2000 ?        S     80:20 /usr/local/bin/zmc -d /dev/video2`

I am not sure why, i believe its because its possible to use the same device by two(or more) monitors, but each one on a different channel.

**Comment by connortechnology** [comment]
Okay, I'm fine with loading by -d... but all the host, password, etc...  what use?

**Comment by connortechnology** [comment]
or better yet, replace them with a url parameter.

**Comment by knnniggett** [comment]
Merging this for 1.30.3. Please create another pr if it is decided to make further changes.

**Pull request merged**
