### PR TITLE
Add Control plugin for PTZ cameras supporting the PSIA IP Media Device API

### PR DESCRIPTION
**Pull request by jof**
I did some experimentation and got this control plugin working with my Trendnet TVIP450PI outdoor dome PTZ camera.

The control protocol is based on the Physical Security Interoperability Alliance, IP Media Device API Specification.

This PR is a rename and largely similar to #2185

### CODE REVIEW

**Comment by connortechnology** [comment]
No need for new PR's.  Just push to the branch and the PR will auto-update.

A few notes: please uncomment the use strict.  Please update the documentation to be similar to what I have done in Trendnet.pm.  The AUTOLOAD and new subs are not required they will be inherited. 

Your code assumes http instead of https.  

No db version updates are required.

**Comment by jof** [comment]
I opened a new PR to point it at a new branch name that is more clear about what is being added (PSIA vs a specific trendnet model).

I updated the http(s)? protocol detection for URL generation.

I also updated the license, per @knight-of-ni's suggestion from #2192

**Comment by knight-of-ni** [comment]
@jof Just confirming with you that this PR has been superseded by another and can be closed.

**Comment by connortechnology** [comment]
No I think this is for TrendNet cameras, the other was Dahua.  I think this looks good for merging.

**Comment by knight-of-ni** [comment]
Got it. I resolved the conflicts. Merging.

**Pull request merged**
