### PR TITLE
feat(sound): Include default alarm sound

### PR DESCRIPTION
**Pull request by Simpler1**

### CODE REVIEW

**Comment by connortechnology** [comment]
@onlyjob are you able to comment on our ability to include this sound bit? It comes from : https://mixkit.co/free-sound-effects/click/  

Items under the Mixkit Sound Effects Free License can be used in your commercial and non-commercial projects for free.

You are licensed to use the Item to create an End Product that incorporates the Item as well as other things, so that it is larger in scope and different in nature than the Item. You’re permitted to download, copy, modify, distribute and publicly perform the Sound Effect Items on any web or social media platform, in podcasts and in video games, as well as in films and presentations distributed on CDs, DVDs, via TV or radio broadcast or internet based video on demand services.

You can’t redistribute the Item on its own, as stock, in a tool or template, or with source files. You’re also not allowed to claim them as your own or register them on any rights management service.

There are some important limits to these rights, described in our User Terms.

**Comment by Simpler1** [comment]
@connortechnology I did not intend to force push this into master.  I'm not sure how to undo this (or if that is even necessary).

**Comment by connortechnology** [comment]
Very weird... I can't reopen it either.

**Comment by Simpler1** [comment]
Hmm... Maybe best for me to just create a new pull request.

**Pull request closed without merging**
