### PR TITLE
Adds logic to handle ports / unix socket

### PR DESCRIPTION
**Pull request by josh4trunks**
Logic is added to handle ports / unix file sockets for database connection.

For example the following now all work as expected
```
ZM_DB_HOST=localhost
ZM_DB_HOST=REMOTE_HOST:1234
ZM_DB_HOST=localhost:/path/to/non-default.sock
```

Fixes https://github.com/ZoneMinder/ZoneMinder/issues/901

### CODE REVIEW

**Comment by josh4trunks** [comment]
I'm not sure why Zoneminder has 3 different Perl files  and 2 different C++ files that connect to the database? If it's not necessary maybe we can consolidate the connections a bit?

**Comment by josh4trunks** [comment]
@knnniggett @connortechnology

**Comment by josh4trunks** [comment]
Please don't merge yet.
Looks like the API doesn't know how to handle the mysql connection. Anyone know where the connection is being initiated so I can fix it?

**Comment by SteveGilvarry** [comment]
https://github.com/ZoneMinder/ZoneMinder/blob/master/web/api/app/Config/database.php.default

**Comment by josh4trunks** [comment]
Thanks, I'll work on fixing this issue up when I get a chance

**Comment by connortechnology** [comment]
I have a PR coming today that improves the api db config. you might want to wait on it

**Comment by connortechnology** [comment]
You might want to base your changes off my pr #1458

**Comment by josh4trunks** [comment]
sounds, good I'll wait. I gotta figure out the cake part anyway

**Comment by josh4trunks** [comment]
@SteveGilvarry It looks like web/api/app/Config/database.php is installed during installation using the default values. If an admin is using any non-default database connect parameters (host/port/user/pass) are they supposed to edit this file as well as their zm.conf?

Maybe we should re-implement this so database.php just pulls the values from the zm.conf?

Here's an example giving parameters to a different framework, but looks similar and in this case the values are dynamic.
https://github.com/nZEDb/nZEDb/blob/0.x/app/config/bootstrap/connections.php

**Comment by SteveGilvarry** [comment]
API is early stages of implementation so I assume no one has hit this yet,
but you would think a single place for all settings would make more sense.
I suspect database.php is cakephp out of the box.

**Comment by connortechnology** [comment]
See #1470 which does exactly that.

**Comment by josh4trunks** [comment]
sweet, DB_SOCKET is missing though

**Comment by josh4trunks** [comment]
Replaced by https://github.com/ZoneMinder/ZoneMinder/pull/1492

**Pull request closed without merging**
