### PR TITLE
Added control script for SunEyes SP-P1802SWPTZ

### PR DESCRIPTION
**Pull request by bofhdk**
(http://www.amazon.com/SunEyes-SP-P1802SWPTZ-Wireless-Camera-1080P/dp/B00MOTBXK6)

### CODE REVIEW

**Comment by knnniggett** [comment]
Thank you for taking the time to contribute. However, you also need to add the necessary sql bits. Otherwise, it won't show up in the console. 

Like so:
https://github.com/ZoneMinder/ZoneMinder/blob/master/db/zm_create.sql.in#L587

**Comment by bofhdk** [comment]
ahh! - sorry for the omission - it's on it's way through now :)

Thanks for the tip-off :)


/bobby

**Comment by bofhdk** [comment]
Oh - MonitorPresets too .... coming through.

(one day I'll get the hang of this stuff (I hope) :) )

**Comment by knnniggett** [comment]
Nice work.

**Comment by bofhdk** [comment]
Thanks :)

**Pull request merged**
