### PR TITLE
arm neon-check "uname -m" if CMAKE_SYSTEM_PROCESSOR is not what we expect

### LINKED ISSUE #1952: Arm Neon code fails to build on the raspberry pi 3
**ZoneMinder Version (`zmaudit.pl -v`):**
1.31.1

**Are you using a development snapshot / git checkout?  If so, what is the latest commit? (`git rev-parse HEAD`):**

b5cdc5d9af6764ac8d1b1bccee78ef34c14c3126
** I am using a fork of ZoneMinder branch motion_vectors

**Linux Distribution and Version (`cat /etc/os-release` or `cat /etc/redhat-release`):**
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Relevant log lines:**

make[1]: Entering directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[2]: Entering directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[3]: Entering directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[3]: Leaving directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[3]: Entering directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
[  1%] Building CXX object src/CMakeFiles/zm.dir/zm_image.cpp.o
/mnt/DISK1/build/ZoneMinder/src/zm_image.cpp:3418:128: warning: target attribute is not supported on this machine [-Wattributes]
 void neon32_armv7_fastblend(const uint8_t* col1, const uint8_t* col2, uint8_t* result, unsigned long count, double blendpercent) {
                                                                                                                                ^
/mnt/DISK1/build/ZoneMinder/src/zm_image.cpp:3809:110: warning: target attribute is not supported on this machine [-Wattributes]
 void neon32_armv7_delta8_gray8(const uint8_t* col1, const uint8_t* col2, uint8_t* result, unsigned long count) {
                                                                                                              ^
/mnt/DISK1/build/ZoneMinder/src/zm_image.cpp:3885:131: warning: target attribute is not supported on this machine [-Wattributes]
 void neon32_armv7_delta8_rgb32(const uint8_t* col1, const uint8_t* col2, uint8_t* result, unsigned long count, uint32_t multiplier) {
                                                                                                                                   ^
{standard input}: Assembler messages:
{standard input}:364: Error: selected processor does not support ARM mode `vdup.8 q12,r12'
{standard input}:370: Error: selected processor does not support ARM mode `vrshl.u8 q8,q0,q12'
{standard input}:371: Error: selected processor does not support ARM mode `vrshl.u8 q9,q1,q12'
{standard input}:372: Error: selected processor does not support ARM mode `vrshl.u8 q10,q2,q12'
{standard input}:373: Error: selected processor does not support ARM mode `vrshl.u8 q11,q3,q12'
{standard input}:374: Error: selected processor does not support ARM mode `vrshl.u8 q4,q4,q12'
{standard input}:375: Error: selected processor does not support ARM mode `vrshl.u8 q5,q5,q12'
{standard input}:376: Error: selected processor does not support ARM mode `vrshl.u8 q6,q6,q12'
{standard input}:377: Error: selected processor does not support ARM mode `vrshl.u8 q7,q7,q12'
{standard input}:378: Error: selected FPU does not support instruction -- `vsub.i8 q4,q4,q8'
{standard input}:379: Error: selected FPU does not support instruction -- `vsub.i8 q5,q5,q9'
{standard input}:380: Error: selected FPU does not support instruction -- `vsub.i8 q6,q6,q10'
{standard input}:381: Error: selected FPU does not support instruction -- `vsub.i8 q7,q7,q11'
{standard input}:382: Error: selected FPU does not support instruction -- `vadd.i8 q4,q4,q0'
{standard input}:383: Error: selected FPU does not support instruction -- `vadd.i8 q5,q5,q1'
{standard input}:384: Error: selected FPU does not support instruction -- `vadd.i8 q6,q6,q2'
{standard input}:385: Error: selected FPU does not support instruction -- `vadd.i8 q7,q7,q3'
{standard input}:1878: Error: selected processor does not support ARM mode `vabd.u8 q0,q0,q4'
{standard input}:1879: Error: selected processor does not support ARM mode `vabd.u8 q1,q1,q5'
{standard input}:1880: Error: selected processor does not support ARM mode `vabd.u8 q2,q2,q6'
{standard input}:1881: Error: selected processor does not support ARM mode `vabd.u8 q3,q3,q7'
{standard input}:33683: Error: selected processor does not support ARM mode `vdup.32 q8,r12'
{standard input}:33689: Error: selected processor does not support ARM mode `vabd.u8 q0,q0,q4'
{standard input}:33690: Error: selected processor does not support ARM mode `vabd.u8 q1,q1,q5'
{standard input}:33691: Error: selected processor does not support ARM mode `vabd.u8 q2,q2,q6'
{standard input}:33692: Error: selected processor does not support ARM mode `vabd.u8 q3,q3,q7'
{standard input}:33693: Error: selected processor does not support ARM mode `vrshr.u8 q0,q0,#3'
{standard input}:33694: Error: selected processor does not support ARM mode `vrshr.u8 q1,q1,#3'
{standard input}:33695: Error: selected processor does not support ARM mode `vrshr.u8 q2,q2,#3'
{standard input}:33696: Error: selected processor does not support ARM mode `vrshr.u8 q3,q3,#3'
{standard input}:33697: Error: selected FPU does not support instruction -- `vmul.i8 q0,q0,q8'
{standard input}:33698: Error: selected FPU does not support instruction -- `vmul.i8 q1,q1,q8'
{standard input}:33699: Error: selected FPU does not support instruction -- `vmul.i8 q2,q2,q8'
{standard input}:33700: Error: selected FPU does not support instruction -- `vmul.i8 q3,q3,q8'
{standard input}:33701: Error: selected processor does not support ARM mode `vpadd.i8 d0,d0,d1'
{standard input}:33702: Error: selected processor does not support ARM mode `vpadd.i8 d2,d2,d3'
{standard input}:33703: Error: selected processor does not support ARM mode `vpadd.i8 d4,d4,d5'
{standard input}:33704: Error: selected processor does not support ARM mode `vpadd.i8 d6,d6,d7'
{standard input}:33705: Error: selected processor does not support ARM mode `vpadd.i8 d0,d0,d0'
{standard input}:33706: Error: selected processor does not support ARM mode `vpadd.i8 d1,d2,d2'
{standard input}:33707: Error: selected processor does not support ARM mode `vpadd.i8 d2,d4,d4'
{standard input}:33708: Error: selected processor does not support ARM mode `vpadd.i8 d3,d6,d6'
{standard input}:33709: Error: selected processor does not support ARM mode `vst4.32 {d0[0],d1[0],d2[0],d3[0]},[r2]!'
src/CMakeFiles/zm.dir/build.make:398: recipe for target 'src/CMakeFiles/zm.dir/zm_image.cpp.o' failed
make[3]: *** [src/CMakeFiles/zm.dir/zm_image.cpp.o] Error 1
make[3]: Leaving directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
CMakeFiles/Makefile2:162: recipe for target 'src/CMakeFiles/zm.dir/all' failed
make[2]: *** [src/CMakeFiles/zm.dir/all] Error 2
make[2]: Leaving directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/mnt/DISK1/build/ZoneMinder/obj-arm-linux-gnueabihf'
dh_auto_build: make -j1 returned exit code 2
debian/rules:45: recipe for target 'build' failed
make: *** [build] Error 2

### PR DESCRIPTION
**Pull request by knnniggett**
fixes #1952 

@mastertheknife you around? Would like your feedback

@cmisip can you test this and confirm ZoneMinder builds now on Raspbian?

### CODE REVIEW

**Comment by mastertheknife** [comment]
I am around :)
This looks okay to me, but its probably best to only do this detection if CMAKE_SYSTEM_NAME matches "Linux".
If we're not running Linux, it might fail, and the code below only cares if its Linux anyway.

**Comment by knnniggett** [comment]
Updated to exclude non-Linux environments, but I did add a note to contact us if someone does want to add neon support for arm hardware running a non-Linux distro. I don't see why this won't work on FreeBSD for example.

@cmisip Please test this and verify it works on your system.

**Comment by cmisip** [comment]
It doesn't finnish building.  Sorry for the late response.  

`pi@raspberrypi:~/build/ZoneMinder $ dpkg-buildpackage -us -uc -nc -rfakeroot -b
dpkg-buildpackage: source package zoneminder
dpkg-buildpackage: source version 1.28.108-nmu2015100101
dpkg-buildpackage: source distribution wheezy
dpkg-buildpackage: source changed by Isaac Connor <iconnor@connortechnology.com>
dpkg-buildpackage: host architecture armhf
 dpkg-source --before-build ZoneMinder
 debian/rules build
dh build --buildsystem=cmake --parallel
   dh_auto_build -O--buildsystem=cmake -O--parallel
	make -j1
make[1]: Entering directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[2]: Entering directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[3]: Entering directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[3]: Leaving directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
make[3]: Entering directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
[  1%] Building CXX object src/CMakeFiles/zm.dir/zm_image.cpp.o
/home/pi/build/ZoneMinder/src/zm_image.cpp:3378:128: warning: target attribute is not supported on this machine [-Wattributes]
 void neon32_armv7_fastblend(const uint8_t* col1, const uint8_t* col2, uint8_t* result, unsigned long count, double blendpercent) {
                                                                                                                                ^
/home/pi/build/ZoneMinder/src/zm_image.cpp:3769:110: warning: target attribute is not supported on this machine [-Wattributes]
 void neon32_armv7_delta8_gray8(const uint8_t* col1, const uint8_t* col2, uint8_t* result, unsigned long count) {
                                                                                                              ^
/home/pi/build/ZoneMinder/src/zm_image.cpp:3845:131: warning: target attribute is not supported on this machine [-Wattributes]
 void neon32_armv7_delta8_rgb32(const uint8_t* col1, const uint8_t* col2, uint8_t* result, unsigned long count, uint32_t multiplier) {
                                                                                                                                   ^
{standard input}: Assembler messages:
{standard input}:364: Error: selected processor does not support ARM mode `vdup.8 q12,r12'
{standard input}:370: Error: selected processor does not support ARM mode `vrshl.u8 q8,q0,q12'
{standard input}:371: Error: selected processor does not support ARM mode `vrshl.u8 q9,q1,q12'
{standard input}:372: Error: selected processor does not support ARM mode `vrshl.u8 q10,q2,q12'
{standard input}:373: Error: selected processor does not support ARM mode `vrshl.u8 q11,q3,q12'
{standard input}:374: Error: selected processor does not support ARM mode `vrshl.u8 q4,q4,q12'
{standard input}:375: Error: selected processor does not support ARM mode `vrshl.u8 q5,q5,q12'
{standard input}:376: Error: selected processor does not support ARM mode `vrshl.u8 q6,q6,q12'
{standard input}:377: Error: selected processor does not support ARM mode `vrshl.u8 q7,q7,q12'
{standard input}:378: Error: selected FPU does not support instruction -- `vsub.i8 q4,q4,q8'
{standard input}:379: Error: selected FPU does not support instruction -- `vsub.i8 q5,q5,q9'
{standard input}:380: Error: selected FPU does not support instruction -- `vsub.i8 q6,q6,q10'
{standard input}:381: Error: selected FPU does not support instruction -- `vsub.i8 q7,q7,q11'
{standard input}:382: Error: selected FPU does not support instruction -- `vadd.i8 q4,q4,q0'
{standard input}:383: Error: selected FPU does not support instruction -- `vadd.i8 q5,q5,q1'
{standard input}:384: Error: selected FPU does not support instruction -- `vadd.i8 q6,q6,q2'
{standard input}:385: Error: selected FPU does not support instruction -- `vadd.i8 q7,q7,q3'
{standard input}:1878: Error: selected processor does not support ARM mode `vabd.u8 q0,q0,q4'
{standard input}:1879: Error: selected processor does not support ARM mode `vabd.u8 q1,q1,q5'
{standard input}:1880: Error: selected processor does not support ARM mode `vabd.u8 q2,q2,q6'
{standard input}:1881: Error: selected processor does not support ARM mode `vabd.u8 q3,q3,q7'
{standard input}:33620: Error: selected processor does not support ARM mode `vdup.32 q8,r12'
{standard input}:33626: Error: selected processor does not support ARM mode `vabd.u8 q0,q0,q4'
{standard input}:33627: Error: selected processor does not support ARM mode `vabd.u8 q1,q1,q5'
{standard input}:33628: Error: selected processor does not support ARM mode `vabd.u8 q2,q2,q6'
{standard input}:33629: Error: selected processor does not support ARM mode `vabd.u8 q3,q3,q7'
{standard input}:33630: Error: selected processor does not support ARM mode `vrshr.u8 q0,q0,#3'
{standard input}:33631: Error: selected processor does not support ARM mode `vrshr.u8 q1,q1,#3'
{standard input}:33632: Error: selected processor does not support ARM mode `vrshr.u8 q2,q2,#3'
{standard input}:33633: Error: selected processor does not support ARM mode `vrshr.u8 q3,q3,#3'
{standard input}:33634: Error: selected FPU does not support instruction -- `vmul.i8 q0,q0,q8'
{standard input}:33635: Error: selected FPU does not support instruction -- `vmul.i8 q1,q1,q8'
{standard input}:33636: Error: selected FPU does not support instruction -- `vmul.i8 q2,q2,q8'
{standard input}:33637: Error: selected FPU does not support instruction -- `vmul.i8 q3,q3,q8'
{standard input}:33638: Error: selected processor does not support ARM mode `vpadd.i8 d0,d0,d1'
{standard input}:33639: Error: selected processor does not support ARM mode `vpadd.i8 d2,d2,d3'
{standard input}:33640: Error: selected processor does not support ARM mode `vpadd.i8 d4,d4,d5'
{standard input}:33641: Error: selected processor does not support ARM mode `vpadd.i8 d6,d6,d7'
{standard input}:33642: Error: selected processor does not support ARM mode `vpadd.i8 d0,d0,d0'
{standard input}:33643: Error: selected processor does not support ARM mode `vpadd.i8 d1,d2,d2'
{standard input}:33644: Error: selected processor does not support ARM mode `vpadd.i8 d2,d4,d4'
{standard input}:33645: Error: selected processor does not support ARM mode `vpadd.i8 d3,d6,d6'
{standard input}:33646: Error: selected processor does not support ARM mode `vst4.32 {d0[0],d1[0],d2[0],d3[0]},[r2]!'
src/CMakeFiles/zm.dir/build.make:422: recipe for target 'src/CMakeFiles/zm.dir/zm_image.cpp.o' failed
make[3]: *** [src/CMakeFiles/zm.dir/zm_image.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
CMakeFiles/Makefile2:162: recipe for target 'src/CMakeFiles/zm.dir/all' failed
make[2]: *** [src/CMakeFiles/zm.dir/all] Error 2
make[2]: Leaving directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/build/ZoneMinder/obj-arm-linux-gnueabihf'
dh_auto_build: make -j1 returned exit code 2
debian/rules:44: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
`

**Comment by cmisip** [comment]
It doesn't finnish building.  I put the details on the issue page of
ZoneMinder github.  Sorry for the late response.

Chris

**Comment by knnniggett** [comment]
@cmisip Make sure you are building the latest master branch commit 613bbfb65bb18206542f5dba50e618d70d5e94c3 or newer. If you are building from a fork, then you have to merge the changes from the zoneminder master branch into that fork.

**Comment by cmisip** [comment]
This is from a fresh git clone and checkout master.

Chris

**Comment by knnniggett** [comment]
The cmake output is missing from your build output so we can't see what happened. 

Try following these instructions to build a zoneminder deb:
http://zoneminder.readthedocs.io/en/latest/installationguide/ubuntu.html#harder-way-build-package-from-source

This will work for debian as well as ubuntu. Build the stock ZoneMinder master branch first just to see if it builds.

**Comment by knnniggett** [comment]
Building the master branch previously on an odroid xu4 running armbian (debian jessie) worked without issue. I will install raspbian on a spare raspberry pi 2 to try and troubleshoot the issue further.

**Pull request merged**
