### PR TITLE
478 Basic ONVIF Support

### PR DESCRIPTION
**Pull request by altaroca**
I added basic onvif support. Please find details here: https://altaroca.wordpress.com
It includes an almost complete ONVIF API. That should explain the huge number of files.

### CODE REVIEW

**Comment by liucougar** [comment]
is it easier to use https://github.com/ltoscano/ponvif as the onvif client library?

**Comment by altaroca** [comment]
that library supports only a small subset of the onvif specifications.

**Comment by knnniggett** [comment]
Guys, this has been a long time coming, and my apologies for not merging this sooner.
ONVIF support has been added, but support for it is off by default.
You have to set --enable-onvif=yes flag in autotools or ZM_ONVIF=ON flag in cmake.

**Comment by connortechnology** [comment]
excellent work. I believe one of my cameras does onvif so I will test.

**Comment by knnniggett** [comment]
TO DO:
- Need to add the ONVIF PTZ camera control type to a zm_update-1.28.2.sql
- Need to disable the link to the ONVIF probe when support is not compiled in
- Need to document how to use it within the zoneminder.  Maybe we just link to the author's homepage.

**Pull request merged**
