### PR TITLE
more perlcritic/PBP corrections

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by knnniggett** [comment]
Looks like Travis failed the build.  Here is the relevant error:
```Travis
$ sudo zmpkg.pl start
Warning, overriding installed ./zm.conf file with local copy
Global symbol "$LOGFILE" requires explicit package name at /usr/share/perl5/ZoneMinder/Logger.pm line 552.
Global symbol "$LOGFILE" requires explicit package name at /usr/share/perl5/ZoneMinder/Logger.pm line 554.
Global symbol "$LOGFILE" requires explicit package name at /usr/share/perl5/ZoneMinder/Logger.pm line 574.
Global symbol "$LOGFILE" requires explicit package name at /usr/share/perl5/ZoneMinder/Logger.pm line 574.
Global symbol "$LOGFILE" requires explicit package name at /usr/share/perl5/ZoneMinder/Logger.pm line 600.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 34.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 34.
Compilation failed in require at /usr/bin/zmpkg.pl line 48.
BEGIN failed--compilation aborted at /usr/bin/zmpkg.pl line 48.
The command "sudo zmpkg.pl start" exited with 2.
```

Think line 552 should read:
```perl
if ( open( my $LOGFILE, ">>", $this->{logFile} ) )
```

**Comment by onlyjob** [comment]
Sorry about that. :( 85d75b0 adds required definition for non-bareword `$LOGFILE` to address this.

**Comment by onlyjob** [comment]
It can't be `my $LOGFILE` because `my` will localise `$LOGFILE` within one particular function while other subroutines are using it too... I've seen that, that's why I didn't add `my` but I've missed the absence of global definition, probably because I'm no longer used to `use 5.006;`...

**Comment by knnniggett** [comment]
Right, good point.

**Pull request merged**
